import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const databaseUrl = process.env.DATABASE_URL ?? "postgresql://sportil:sportil@localhost:5432/sportil";
const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: databaseUrl }),
});

function text(he: string, ru: string, en: string) {
  return { en, he, ru };
}

const checkedAt = new Date("2026-06-18T09:00:00.000Z");
const netanyaMunicipality = text("עיריית נתניה", "Муниципалитет Нетании", "Netanya Municipality");

const sourceUrls = {
  adaptedSport: "https://www.netanya.muni.il/City/SportsAndSociety/PWD/Pages/SpecialNeeds.aspx",
  bialik: "https://www.netanya.muni.il/City/SportsAndSociety/Centers/Pages/Bialik.aspx",
  collegym: "https://collegym.co.il/",
  crossfitGreenBeach: "https://www.crossfitgreenbeach.com/en",
  countryPoleg: "https://www.poleg.org.il/",
  galiYam: "https://www.netanya.muni.il/City/SportsAndSociety/Centers/Pages/galyyam.aspx",
  girlsBasketball:
    "https://www.netanya.muni.il/City/SportsAndSociety/Classes/Pages/ID/GirlsBaketball20.aspx",
  netanyaMunicipality: "https://www.netanya.muni.il/",
  ovadia:
    "https://www.netanya.muni.il/City/SportsAndSociety/facilities/Pages/id/Ovadiahtennis.aspx",
  olimp: "https://www.olimp-swim.com/",
  regaim: "https://www.netanya.muni.il/en/Pages/Regaim.aspx",
  sportek:
    "https://www.netanya.muni.il/City/SportsAndSociety/facilities/Pages/id/sportekiryamimcourt.aspx",
  stakelis: "https://www.netanya.muni.il/City/SportsAndSociety/Centers/Pages/stakelis.aspx",
  tennisClass: "https://www.netanya.muni.il/City/SportsAndSociety/Classes/Pages/ID/Tennis1.aspx",
  topPadel: "https://toppadel.co.il/",
  yeshurun: "https://www.netanya.muni.il/City/SportsAndSociety/Centers/Pages/Yeshurun.aspx",
  yeshurunHall:
    "https://www.netanya.muni.il/City/SportsAndSociety/facilities/Pages/id/Yeshurunvenue.aspx",
};

const organizations = [
  {
    description: text("שכבת המקור העירונית למתקנים וחוגים", "Городской источник объектов и кружков", "Municipal source layer for facilities and classes"),
    id: "org-netanya-municipality",
    kind: "municipality",
    name: netanyaMunicipality,
    sourceType: "official_municipal",
    sourceUrl: sourceUrls.netanyaMunicipality,
    verificationStatus: "active_contact_only",
  },
  {
    description: text("מועדוני פאדל עם הזמנת מגרשים", "Клубы падела с бронированием кортов", "Padel clubs with court booking"),
    id: "org-top-padel",
    kind: "private_club",
    name: text("Top Padel", "Top Padel", "Top Padel"),
    sourceType: "partner_site",
    sourceUrl: sourceUrls.topPadel,
    verificationStatus: "live_bookable",
    websiteUrl: sourceUrls.topPadel,
  },
  {
    description: text("מרכז ספורט רב תחומי במכללת נתניה", "Мультиспортивный центр при академическом колледже Нетании", "Multi-sport center at Netanya Academic College"),
    id: "org-collegym",
    kind: "private_club",
    name: text("קולג'ים", "Collegym", "Collegym"),
    sourceType: "partner_site",
    sourceUrl: sourceUrls.collegym,
    verificationStatus: "live_registration",
    websiteUrl: sourceUrls.collegym,
  },
  {
    description: text("קאנטרי קלאב עם בריכות, מגרשים וחוגים", "Кантри-клуб с бассейнами, кортами и секциями", "Country club with pools, courts, and classes"),
    id: "org-country-poleg",
    kind: "private_club",
    name: text("קאנטרי קלאב פולג", "Country Club Poleg", "Country Club Poleg"),
    sourceType: "partner_site",
    sourceUrl: sourceUrls.countryPoleg,
    verificationStatus: "live_registration",
    websiteUrl: sourceUrls.countryPoleg,
  },
  {
    description: text("רשת מרכזים קהילתיים וחוגים", "Сеть community centers и кружков", "Community center and class network"),
    id: "org-regaim",
    kind: "community_center",
    name: text("רגעים", "Regaim", "Regaim"),
    sourceType: "official_municipal",
    sourceUrl: sourceUrls.regaim,
    verificationStatus: "live_registration",
    websiteUrl: sourceUrls.regaim,
  },
  {
    description: text("מועדון שחייה בקריית השרון נתניה", "Школа и клуб плавания в Кирьят ха-Шарон, Нетания", "Swimming club in Kiryat HaSharon, Netanya"),
    id: "org-olimp-swim",
    kind: "swim_school",
    name: text("אולימפ", "Olimp", "Olimp"),
    sourceType: "partner_site",
    sourceUrl: sourceUrls.olimp,
    verificationStatus: "live_registration",
    websiteUrl: sourceUrls.olimp,
  },
  {
    description: text("מועדון קרוספיט בפולג / גרין ביץ'", "CrossFit box в Полег / Green Beach", "CrossFit box in Poleg / Green Beach"),
    id: "org-crossfit-green-beach",
    kind: "fitness_box",
    name: text("קרוספיט גרין ביץ'", "CrossFit Green Beach", "CrossFit Green Beach"),
    sourceType: "partner_site",
    sourceUrl: sourceUrls.crossfitGreenBeach,
    verificationStatus: "live_registration",
    websiteUrl: sourceUrls.crossfitGreenBeach,
  },
  {
    description: text("ארגון כדורגל פעיל; דף רישום עונתי דורש בדיקת תאריכים", "Активный футбольный клуб; сезонную регистрацию нужно проверить по датам", "Active football club; seasonal registration dates need review"),
    id: "org-maccabi-netanya",
    kind: "sports_association",
    name: text("מכבי נתניה", "Maccabi Netanya", "Maccabi Netanya"),
    sourceType: "sports_association",
    sourceUrl: sourceUrls.netanyaMunicipality,
    verificationStatus: "needs_verification",
  },
] as const;

type SeedVerificationMetadata = {
  bookingMethod?: "contact_request" | "external_registration" | "free_public" | "info_only" | "instant_payment" | "phone_whatsapp";
  confidenceScore?: number;
  externalRegistrationUrl?: string;
  organizationId?: string;
  paymentMethod?: "card_supported" | "external_payment" | "no_payment" | "unknown";
  sourceNotes?: ReturnType<typeof text>;
  sourceType?: "directory" | "external_registration" | "manual_research" | "official_municipal" | "partner_site" | "social" | "sports_association";
  verificationStatus?:
    | "active_contact_only"
    | "archived_closed"
    | "info_only"
    | "live_bookable"
    | "live_registration"
    | "needs_verification";
};

const facilityMetadata: Record<string, SeedVerificationMetadata> = {
  "adapted-sport-tamar-ariel": {
    bookingMethod: "contact_request",
    confidenceScore: 76,
    organizationId: "org-netanya-municipality",
    paymentMethod: "unknown",
    sourceNotes: text("מקור עירוני; נדרש תיאום מקדים רגיש", "Городской источник; требуется бережное предварительное согласование", "Municipal source; needs careful prior coordination"),
    sourceType: "official_municipal",
    verificationStatus: "active_contact_only",
  },
  "bialik-judo": {
    bookingMethod: "contact_request",
    confidenceScore: 74,
    organizationId: "org-netanya-municipality",
    paymentMethod: "unknown",
    sourceNotes: text("מרכז עירוני פעיל, ללא סלוטים חיים", "Активный городской центр без live-слотов", "Active municipal center without live slots"),
    sourceType: "official_municipal",
    verificationStatus: "active_contact_only",
  },
  "collegym-netanya": {
    bookingMethod: "external_registration",
    confidenceScore: 87,
    externalRegistrationUrl: sourceUrls.collegym,
    organizationId: "org-collegym",
    paymentMethod: "external_payment",
    sourceNotes: text("לאחד עם Sports Center at Netanya Academic College; לא ליצור כפילות", "Объединять со Sports Center at Netanya Academic College; не дублировать", "Merge with Netanya Academic College Sports Center; avoid duplicates"),
    sourceType: "partner_site",
    verificationStatus: "live_registration",
  },
  "country-club-poleg": {
    bookingMethod: "external_registration",
    confidenceScore: 86,
    externalRegistrationUrl: sourceUrls.countryPoleg,
    organizationId: "org-country-poleg",
    paymentMethod: "external_payment",
    sourceNotes: text("מועדון רב-תחומי חי; צריך API/יצוא לזמינות אמיתית", "Живой мультиспорт-клуб; нужен API/export для реальной доступности", "Live multi-sport club; needs API/export for real availability"),
    sourceType: "partner_site",
    verificationStatus: "live_registration",
  },
  "crossfit-green-beach": {
    bookingMethod: "external_registration",
    confidenceScore: 84,
    externalRegistrationUrl: sourceUrls.crossfitGreenBeach,
    organizationId: "org-crossfit-green-beach",
    paymentMethod: "external_payment",
    sourceNotes: text("מקור רשמי עם ילדים/נוער ותוכניות כוח", "Официальный источник с kids/youth и силовыми программами", "Official source with kids/youth and strength programs"),
    sourceType: "partner_site",
    verificationStatus: "live_registration",
  },
  "gali-yam-tennis": {
    bookingMethod: "instant_payment",
    confidenceScore: 82,
    organizationId: "org-netanya-municipality",
    paymentMethod: "card_supported",
    sourceNotes: text("סלוט תשלום הוא vertical slice מקומי; סלוטים עירוניים צריכים סנכרון אמיתי", "Платёжный слот является локальным vertical slice; городские слоты требуют синхронизации", "Payment slot is a local vertical slice; municipal slots need real sync"),
    sourceType: "official_municipal",
    verificationStatus: "live_bookable",
  },
  "maccabi-netanya-football-school": {
    bookingMethod: "contact_request",
    confidenceScore: 58,
    organizationId: "org-maccabi-netanya",
    paymentMethod: "unknown",
    sourceNotes: text("דף רישום עונתי פעיל לכאורה, אך יש לבדוק סתירת תאריכים", "Сезонная регистрация выглядит активной, но даты противоречивы", "Season registration appears active, but dates conflict"),
    sourceType: "sports_association",
    verificationStatus: "needs_verification",
  },
  "olimp-swimming-netanya": {
    bookingMethod: "external_registration",
    confidenceScore: 84,
    externalRegistrationUrl: sourceUrls.olimp,
    organizationId: "org-olimp-swim",
    paymentMethod: "external_payment",
    sourceNotes: text("שחייה מגיל 3, קבוצות, שיעורים פרטיים ותחרותי לפי אתר רשמי", "Плавание с 3 лет, группы, частные уроки и спорт по официальному сайту", "Age 3+, groups, private lessons, and competitive swimming per official site"),
    sourceType: "partner_site",
    verificationStatus: "live_registration",
  },
  "ovadia-tennis-courts": {
    bookingMethod: "free_public",
    confidenceScore: 73,
    organizationId: "org-netanya-municipality",
    paymentMethod: "no_payment",
    sourceNotes: text("שימוש ציבורי חופשי; כללי הזמנה מוקדמת דורשים בדיקה", "Публичное использование; правила предварительной записи требуют проверки", "Public use; advance booking rules need verification"),
    sourceType: "official_municipal",
    verificationStatus: "active_contact_only",
  },
  "sportek-ir-yamim-court": {
    bookingMethod: "free_public",
    confidenceScore: 78,
    organizationId: "org-netanya-municipality",
    paymentMethod: "no_payment",
    sourceNotes: text("מגרש ציבורי חינם עם תאורה וחניה לפי מקור עירוני", "Бесплатная публичная площадка с освещением и парковкой по городскому источнику", "Free public court with lighting and parking per municipal source"),
    sourceType: "official_municipal",
    verificationStatus: "info_only",
  },
  "sportek-yahalom": {
    bookingMethod: "free_public",
    confidenceScore: 70,
    organizationId: "org-netanya-municipality",
    paymentMethod: "no_payment",
    sourceNotes: text("פוטסל, מגרש משולב ורולר; עומס הוא הערכה בלבד", "Футзал, combined court и ролики; загрузка только оценочная", "Futsal, combined court, and roller court; load is estimated only"),
    sourceType: "official_municipal",
    verificationStatus: "info_only",
  },
  "stakelis-sports-center": {
    bookingMethod: "contact_request",
    confidenceScore: 72,
    organizationId: "org-netanya-municipality",
    paymentMethod: "unknown",
    sourceNotes: text("מרכז עירוני פעיל; דורש אישור מפעיל ללוחות קבוצות", "Активный городской центр; расписание групп требует подтверждения оператора", "Active municipal center; group schedules need operator confirmation"),
    sourceType: "official_municipal",
    verificationStatus: "active_contact_only",
  },
  "top-padel-ir-yamim": {
    bookingMethod: "external_registration",
    confidenceScore: 88,
    externalRegistrationUrl: sourceUrls.topPadel,
    organizationId: "org-top-padel",
    paymentMethod: "external_payment",
    sourceNotes: text("4 מגרשים בעיר ימים; סימני הזמנה באפליקציה", "4 корта в Ир-Ямим; есть признаки app booking", "4 courts in Ir Yamim; app booking signals"),
    sourceType: "partner_site",
    verificationStatus: "live_bookable",
  },
  "top-padel-poleg": {
    bookingMethod: "external_registration",
    confidenceScore: 86,
    externalRegistrationUrl: sourceUrls.topPadel,
    organizationId: "org-top-padel",
    paymentMethod: "external_payment",
    sourceNotes: text("מיקום פולג / גרין ביץ'; צריך סנכרון סלוטים לפני תשלום מקומי", "Локация Poleg / Green Beach; нужен sync слотов перед локальной оплатой", "Poleg / Green Beach location; slot sync needed before local payment"),
    sourceType: "partner_site",
    verificationStatus: "live_bookable",
  },
  "winter-lake-sports-park": {
    bookingMethod: "free_public",
    confidenceScore: 71,
    organizationId: "org-netanya-municipality",
    paymentMethod: "no_payment",
    sourceNotes: text("אגם החורף: פוטסל, רולר וסקייט; הזמנה מוקדמת לפוטסל דורשת אישור", "Winter Lake: футзал, ролики и скейт; предварительная бронь футзала требует подтверждения", "Winter Lake: futsal, roller, and skate; futsal advance booking needs confirmation"),
    sourceType: "official_municipal",
    verificationStatus: "active_contact_only",
  },
  "yeshurun-basketball": {
    bookingMethod: "contact_request",
    confidenceScore: 77,
    organizationId: "org-netanya-municipality",
    paymentMethod: "unknown",
    sourceNotes: text("מרכז בית ספרי; הזמנת אולם וחוגים צריכים אישור", "Школьный центр; аренда зала и секции требуют подтверждения", "School center; hall use and classes need confirmation"),
    sourceType: "official_municipal",
    verificationStatus: "active_contact_only",
  },
};

const facilities = [
  {
    address: text("בני בנימין 1", "Бней Биньямин 1", "Bnei Binyamin 1"),
    id: "gali-yam-tennis",
    kind: "sport_center",
    name: text("מרכז הטניס גלי ים", "Теннисный центр Гали-Ям", "Gali Yam Tennis Center"),
    neighborhood: text("עיר ימים / גלי ים", "Ир-Ямим / Гали-Ям", "Ir Yamim / Gali Yam"),
    sourceUrl: sourceUrls.galiYam,
    status: "bookable",
  },
  {
    address: text("רחוב עובדיה", "ул. Овадия", "Ovadia Street"),
    id: "ovadia-tennis-courts",
    kind: "court",
    name: text("מגרשי טניס עובדיה", "Теннисные корты Овадия", "Ovadia Tennis Courts"),
    neighborhood: text("נאות גנים", "Неот-Ганим", "Neot Ganim"),
    sourceUrl: sourceUrls.ovadia,
    status: "needs_confirmation",
  },
  {
    address: text("שדרות בן גוריון 170", "проспект Бен-Гурион 170", "Sderot Ben Gurion 170"),
    id: "sportek-ir-yamim-court",
    kind: "public_space",
    name: text("ספורטק עיר ימים", "Спортек Ир-Ямим", "Sportek Ir Yamim"),
    neighborhood: text("עיר ימים", "Ир-Ямим", "Ir Yamim"),
    sourceUrl: sourceUrls.sportek,
    status: "needs_confirmation",
  },
  {
    address: text("שמואל הנציב 45", "Шмуэль ха-Нацив 45", "Shmuel Hanatziv 45"),
    id: "yeshurun-basketball",
    kind: "sport_center",
    name: text("מרכז ספורט ישורון", "Спортивный центр Ешурун", "Yeshurun Sports Center"),
    neighborhood: text("מרכז העיר", "Центр города", "City center"),
    sourceUrl: sourceUrls.yeshurun,
    status: "needs_confirmation",
  },
  {
    address: text("יהודה פרח 11", "Йехуда Перах 11", "Yehuda Perach 11"),
    id: "stakelis-sports-center",
    kind: "sport_center",
    name: text("מרכז ספורט סטקליס", "Спортивный центр Стакелис", "Stakelis Sports Center"),
    neighborhood: text("צפון העיר", "Север города", "North Netanya"),
    sourceUrl: sourceUrls.stakelis,
    status: "needs_confirmation",
  },
  {
    address: text("ביאליק 17", "Бялик 17", "Bialik 17"),
    id: "bialik-judo",
    kind: "program",
    name: text("מרכז ספורט ביאליק - ג'ודו", "Спортивный центр Бялик - дзюдо", "Bialik Sports Center - Judo"),
    neighborhood: text("מרכז העיר", "Центр города", "City center"),
    sourceUrl: sourceUrls.bialik,
    status: "needs_confirmation",
  },
  {
    address: text("בית ספר תמר אריאל / שפירא", "Школа Тамар Ариэль / Шапира", "Tamar Ariel / Shapira School"),
    id: "adapted-sport-tamar-ariel",
    kind: "program",
    name: text("ספורט מותאם - תמר אריאל", "Адаптированный спорт - Тамар Ариэль", "Adapted Sport - Tamar Ariel"),
    neighborhood: text("נתניה", "Нетания", "Netanya"),
    sourceUrl: sourceUrls.adaptedSport,
    status: "needs_confirmation",
  },
  {
    address: text("שדרות בן גוריון 170", "проспект Бен-Гурион 170", "Sderot Ben Gurion 170"),
    id: "top-padel-ir-yamim",
    kind: "court",
    name: text("Top Padel עיר ימים", "Top Padel Ир-Ямим", "Top Padel Ir Yamim"),
    neighborhood: text("עיר ימים", "Ир-Ямим", "Ir Yamim"),
    sourceUrl: sourceUrls.topPadel,
    status: "needs_confirmation",
  },
  {
    address: text("שולמית 3 / מתחם גרין ביץ'", "Шуламит 3 / Green Beach complex", "Shulamit 3 / Green Beach complex"),
    id: "top-padel-poleg",
    kind: "court",
    name: text("Top Padel פולג", "Top Padel Полег", "Top Padel Poleg"),
    neighborhood: text("פולג / גרין ביץ'", "Полег / Green Beach", "Poleg / Green Beach"),
    sourceUrl: sourceUrls.topPadel,
    status: "needs_confirmation",
  },
  {
    address: text("האוניברסיטה 1", "HaUniversita 1", "HaUniversita 1"),
    id: "collegym-netanya",
    kind: "sport_center",
    name: text("קולג'ים - מרכז הספורט במכללת נתניה", "Collegym - спортцентр академического колледжа Нетании", "Collegym - Netanya Academic College Sports Center"),
    neighborhood: text("קריית השרון / המכללה", "Кирьят ха-Шарон / колледж", "Kiryat HaSharon / College"),
    sourceUrl: sourceUrls.collegym,
    status: "needs_confirmation",
  },
  {
    address: text("רמת פולג", "Рамат Полег", "Ramat Poleg"),
    id: "country-club-poleg",
    kind: "sport_center",
    name: text("קאנטרי קלאב פולג", "Country Club Poleg", "Country Club Poleg"),
    neighborhood: text("פולג", "Полег", "Poleg"),
    sourceUrl: sourceUrls.countryPoleg,
    status: "needs_confirmation",
  },
  {
    address: text("שדרות בן גוריון 143", "проспект Бен-Гурион 143", "Sderot Ben Gurion 143"),
    id: "winter-lake-sports-park",
    kind: "public_space",
    name: text("אגם החורף - סקייט, רולר ופוטסל", "Winter Lake - скейт, ролики и футзал", "Winter Lake - Skate, Roller, and Futsal"),
    neighborhood: text("אגם החורף", "Winter Lake", "Winter Lake"),
    sourceUrl: sourceUrls.netanyaMunicipality,
    status: "needs_confirmation",
  },
  {
    address: text("האר\"י / דגניה", "HaAri / Degania", "HaAri / Degania"),
    id: "sportek-yahalom",
    kind: "public_space",
    name: text("ספורטק יהלום", "Спортек Яалом", "Sportek Yahalom"),
    neighborhood: text("יהלום", "Яалом", "Yahalom"),
    sourceUrl: sourceUrls.netanyaMunicipality,
    status: "needs_confirmation",
  },
  {
    address: text("המורן 7", "HaMoran 7", "HaMoran 7"),
    id: "olimp-swimming-netanya",
    kind: "program",
    name: text("אולימפ - מועדון שחייה נתניה", "Olimp - школа плавания Нетания", "Olimp Swimming Club Netanya"),
    neighborhood: text("קריית השרון", "Кирьят ха-Шарон", "Kiryat HaSharon"),
    sourceUrl: sourceUrls.olimp,
    status: "needs_confirmation",
  },
  {
    address: text("שולמית 3", "Шуламит 3", "Shulamit 3"),
    id: "crossfit-green-beach",
    kind: "sport_center",
    name: text("קרוספיט גרין ביץ'", "CrossFit Green Beach", "CrossFit Green Beach"),
    neighborhood: text("פולג / גרין ביץ'", "Полег / Green Beach", "Poleg / Green Beach"),
    sourceUrl: sourceUrls.crossfitGreenBeach,
    status: "needs_confirmation",
  },
  {
    address: text("נתניה", "Нетания", "Netanya"),
    id: "maccabi-netanya-football-school",
    kind: "program",
    name: text("מכבי נתניה - בית ספר לכדורגל", "Maccabi Netanya - футбольная школа", "Maccabi Netanya Football School"),
    neighborhood: text("נתניה", "Нетания", "Netanya"),
    sourceUrl: sourceUrls.netanyaMunicipality,
    status: "needs_confirmation",
  },
] as const;

const sports = [
  { icon: "🎾", id: "tennis", name: text("טניס", "Теннис", "Tennis") },
  { icon: "🏀", id: "basketball", name: text("כדורסל", "Баскетбол", "Basketball") },
  { icon: "⚽", id: "futsal", name: text("קטרגל", "Футзал", "Futsal") },
  { icon: "🥋", id: "taekwondo", name: text("טאקוונדו", "Тхэквондо", "Taekwondo") },
  { icon: "🥋", id: "judo", name: text("ג'ודו", "Дзюдо", "Judo") },
  { icon: "⚽", id: "football", name: text("כדורגל", "Футбол", "Football") },
  { icon: "💃", id: "zumba", name: text("זומבה", "Зумба", "Zumba") },
  { icon: "🤸", id: "capoeira", name: text("קפוארה", "Капоэйра", "Capoeira") },
  { icon: "♿", id: "adapted_sport", name: text("ספורט מותאם", "Адаптированный спорт", "Adapted sport") },
  { icon: "🎾", id: "padel", name: text("פאדל", "Падел", "Padel") },
  { icon: "🏊", id: "swimming", name: text("שחייה", "Плавание", "Swimming") },
  { icon: "🛼", id: "roller_skating", name: text("רולר", "Ролики", "Roller skating") },
  { icon: "🛹", id: "skateboarding", name: text("סקייטבורד", "Скейтборд", "Skateboarding") },
  { icon: "🏋️", id: "crossfit", name: text("קרוספיט", "Кроссфит", "CrossFit") },
  { icon: "🤸", id: "gymnastics", name: text("התעמלות", "Гимнастика", "Gymnastics") },
  { icon: "💃", id: "dance", name: text("מחול", "Танцы", "Dance") },
  { icon: "🏓", id: "table_tennis", name: text("טניס שולחן", "Настольный теннис", "Table tennis") },
  { icon: "🏸", id: "badminton", name: text("בדמינטון", "Бадминтон", "Badminton") },
  { icon: "🥋", id: "karate", name: text("קראטה", "Карате", "Karate") },
  { icon: "🥋", id: "krav_maga", name: text("קרב מגע", "Крав-мага", "Krav Maga") },
  { icon: "💪", id: "fitness", name: text("כושר", "Фитнес", "Fitness") },
] as const;

const spaces = [
  {
    capacity: 4,
    description: text("מגרש טניס חיצוני", "Открытый теннисный корт", "Outdoor tennis court"),
    facilityId: "gali-yam-tennis",
    id: "gali-yam-court-01-space",
    indoor: false,
    name: text("מגרש 1", "Корт 1", "Court 1"),
    surface: text("משטח קשיח", "Хард", "Hard court"),
  },
  {
    capacity: 12,
    description: text("אזור אימון לחוגים", "Тренировочная зона для секций", "Training area for classes"),
    facilityId: "gali-yam-tennis",
    id: "gali-yam-training-courts",
    indoor: false,
    name: text("אזור אימון ילדים", "Детская тренировочная зона", "Children training area"),
    surface: text("משטח קשיח", "Хард", "Hard court"),
  },
  {
    capacity: 2,
    description: text("מגרשי טניס ציבוריים", "Публичные теннисные корты", "Public tennis courts"),
    facilityId: "ovadia-tennis-courts",
    id: "ovadia-public-courts-space",
    indoor: false,
    name: text("מגרשי עובדיה", "Корты Овадия", "Ovadia courts"),
    surface: text("משטח קשיח", "Хард", "Hard court"),
  },
  {
    capacity: 20,
    description: text("מגרש ציבורי משולב", "Комбинированная общественная площадка", "Combined public court"),
    facilityId: "sportek-ir-yamim-court",
    id: "sportek-combined-court-space",
    indoor: false,
    name: text("מגרש משולב", "Комбинированная площадка", "Combined court"),
    surface: text("אספלט ספורט", "Спортивный асфальт", "Sport asphalt"),
  },
  {
    capacity: 24,
    description: text("אולם בית ספרי רב שימושי", "Школьный многоцелевой зал", "School multi-use hall"),
    facilityId: "yeshurun-basketball",
    id: "yeshurun-main-hall",
    indoor: true,
    name: text("אולם מרכזי", "Главный зал", "Main hall"),
    surface: text("פרקט / PVC", "Паркет / PVC", "Wood / PVC"),
  },
  {
    capacity: 20,
    description: text("אולם פעילות בית ספרי", "Школьный спортивный зал", "School activity hall"),
    facilityId: "stakelis-sports-center",
    id: "stakelis-gym-space",
    indoor: true,
    name: text("אולם סטקליס", "Зал Стакелис", "Stakelis hall"),
    surface: text("אולם", "Зал", "Hall"),
  },
  {
    capacity: 14,
    description: text("אזור אומנויות לחימה", "Зона единоборств", "Martial arts area"),
    facilityId: "bialik-judo",
    id: "bialik-dojo-space",
    indoor: true,
    name: text("דוג'ו ביאליק", "Додзё Бялик", "Bialik dojo"),
    surface: text("מזרנים", "Татами", "Mats"),
  },
  {
    capacity: 12,
    description: text("חלל מותאם לפעילות קטנה", "Адаптированное пространство для малых групп", "Adapted small-group space"),
    facilityId: "adapted-sport-tamar-ariel",
    id: "tamar-ariel-adapted-space",
    indoor: true,
    name: text("חלל מותאם", "Адаптированный зал", "Adapted hall"),
    surface: text("אולם", "Зал", "Hall"),
  },
  {
    capacity: 4,
    description: text("מגרש פאדל חיצוני להזמנה זוגית", "Открытый корт падела для парной игры", "Outdoor padel court for doubles"),
    facilityId: "top-padel-ir-yamim",
    id: "top-padel-ir-yamim-court-01",
    indoor: false,
    name: text("מגרש פאדל 1", "Корт падела 1", "Padel court 1"),
    surface: text("דשא סינתטי", "Искусственная трава", "Artificial turf"),
  },
  {
    capacity: 4,
    description: text("מגרש פאדל במתחם גרין ביץ'", "Корт падела в Green Beach complex", "Padel court at Green Beach complex"),
    facilityId: "top-padel-poleg",
    id: "top-padel-poleg-court-01",
    indoor: false,
    name: text("מגרש פאדל פולג", "Корт падела Полег", "Poleg padel court"),
    surface: text("דשא סינתטי", "Искусственная трава", "Artificial turf"),
  },
  {
    capacity: 20,
    description: text("בריכה מחוממת חצי אולימפית", "Крытый подогреваемый полуолимпийский бассейн", "Heated half-Olympic indoor pool"),
    facilityId: "collegym-netanya",
    id: "collegym-pool",
    indoor: true,
    name: text("בריכה חצי אולימפית", "Полуолимпийский бассейн", "Half-Olympic pool"),
    surface: text("מים", "Вода", "Water"),
  },
  {
    capacity: 4,
    description: text("שני מגרשי טניס במתחם", "Теннисные корты комплекса", "Tennis courts in the complex"),
    facilityId: "collegym-netanya",
    id: "collegym-tennis-courts",
    indoor: false,
    name: text("מגרשי טניס", "Теннисные корты", "Tennis courts"),
    surface: text("משטח קשיח", "Хард", "Hard court"),
  },
  {
    capacity: 18,
    description: text("אולמות סטודיו וחוגי ילדים", "Студии и детские секции", "Studios and children classes"),
    facilityId: "collegym-netanya",
    id: "collegym-studios",
    indoor: true,
    name: text("סטודיו חוגים", "Студия секций", "Classes studio"),
    surface: text("סטודיו", "Студия", "Studio"),
  },
  {
    capacity: 16,
    description: text("בריכות וחוגי שחייה", "Бассейны и уроки плавания", "Pools and swimming classes"),
    facilityId: "country-club-poleg",
    id: "country-poleg-pool",
    indoor: true,
    name: text("בריכות שחייה", "Бассейны", "Swimming pools"),
    surface: text("מים", "Вода", "Water"),
  },
  {
    capacity: 4,
    description: text("ארבעה מגרשי טניס לפי research", "Четыре теннисных корта по research", "Four tennis courts per research"),
    facilityId: "country-club-poleg",
    id: "country-poleg-tennis-courts",
    indoor: false,
    name: text("מגרשי טניס", "Теннисные корты", "Tennis courts"),
    surface: text("משטח קשיח", "Хард", "Hard court"),
  },
  {
    capacity: 20,
    description: text("מגרש פוטסל סינתטי ציבורי", "Публичное синтетическое поле футзала", "Public synthetic futsal field"),
    facilityId: "winter-lake-sports-park",
    id: "winter-lake-futsal-field",
    indoor: false,
    name: text("מגרש פוטסל", "Поле футзала", "Futsal field"),
    surface: text("דשא סינתטי", "Искусственная трава", "Synthetic grass"),
  },
  {
    capacity: 30,
    description: text("סקייטפארק ציבורי עם מתקני אקסטרים", "Публичный скейтпарк с extreme facilities", "Public skatepark with extreme facilities"),
    facilityId: "winter-lake-sports-park",
    id: "winter-lake-skatepark",
    indoor: false,
    name: text("סקייטפארק", "Скейтпарк", "Skatepark"),
    surface: text("בטון", "Бетон", "Concrete"),
  },
  {
    capacity: 18,
    description: text("מגרש רולר ציבורי", "Публичная роллер-площадка", "Public roller court"),
    facilityId: "sportek-yahalom",
    id: "sportek-yahalom-roller-court",
    indoor: false,
    name: text("מגרש רולר", "Роллер-площадка", "Roller court"),
    surface: text("אספלט ספורט", "Спортивный асфальт", "Sport asphalt"),
  },
  {
    capacity: 20,
    description: text("מגרש משולב ופוטסל", "Комбинированная площадка и футзал", "Combined court and futsal"),
    facilityId: "sportek-yahalom",
    id: "sportek-yahalom-combined",
    indoor: false,
    name: text("מגרש משולב", "Комбинированная площадка", "Combined court"),
    surface: text("אספלט ספורט", "Спортивный асфальт", "Sport asphalt"),
  },
  {
    capacity: 12,
    description: text("קבוצות שחייה ושיעורים פרטיים", "Группы плавания и частные уроки", "Swimming groups and private lessons"),
    facilityId: "olimp-swimming-netanya",
    id: "olimp-swim-lanes",
    indoor: true,
    name: text("מסלולי שחייה", "Дорожки бассейна", "Swim lanes"),
    surface: text("מים", "Вода", "Water"),
  },
  {
    capacity: 16,
    description: text("אימון קרוספיט indoor/outdoor", "Тренировки CrossFit indoor/outdoor", "Indoor/outdoor CrossFit training"),
    facilityId: "crossfit-green-beach",
    id: "crossfit-green-beach-floor",
    indoor: false,
    name: text("רחבת אימון", "Тренировочная зона", "Training floor"),
    surface: text("משטח פונקציונלי", "Функциональное покрытие", "Functional training surface"),
  },
  {
    capacity: 18,
    description: text("בית ספר לכדורגל וקבוצות גיל", "Футбольная школа и возрастные группы", "Football school and age groups"),
    facilityId: "maccabi-netanya-football-school",
    id: "maccabi-netanya-football-training",
    indoor: false,
    name: text("מגרש אימון", "Тренировочное поле", "Training field"),
    surface: text("דשא / סינתטי", "Трава / синтетика", "Grass / synthetic"),
  },
] as const;

const spaceSportCapabilities = [
  { spaceId: "gali-yam-court-01-space", sportId: "tennis" },
  { spaceId: "gali-yam-training-courts", sportId: "tennis" },
  { spaceId: "ovadia-public-courts-space", sportId: "tennis" },
  { spaceId: "sportek-combined-court-space", sportId: "basketball" },
  { spaceId: "sportek-combined-court-space", sportId: "futsal" },
  { spaceId: "yeshurun-main-hall", sportId: "basketball" },
  { spaceId: "yeshurun-main-hall", sportId: "futsal" },
  { spaceId: "stakelis-gym-space", sportId: "taekwondo" },
  { spaceId: "stakelis-gym-space", sportId: "basketball" },
  { spaceId: "bialik-dojo-space", sportId: "judo" },
  { spaceId: "tamar-ariel-adapted-space", sportId: "adapted_sport" },
  { spaceId: "tamar-ariel-adapted-space", sportId: "basketball" },
  { spaceId: "tamar-ariel-adapted-space", sportId: "football" },
  { spaceId: "tamar-ariel-adapted-space", sportId: "zumba" },
  { spaceId: "tamar-ariel-adapted-space", sportId: "capoeira" },
  { spaceId: "top-padel-ir-yamim-court-01", sportId: "padel" },
  { spaceId: "top-padel-poleg-court-01", sportId: "padel" },
  { spaceId: "collegym-pool", sportId: "swimming" },
  { spaceId: "collegym-tennis-courts", sportId: "tennis" },
  { spaceId: "collegym-studios", sportId: "judo" },
  { spaceId: "collegym-studios", sportId: "capoeira" },
  { spaceId: "collegym-studios", sportId: "football" },
  { spaceId: "collegym-studios", sportId: "basketball" },
  { spaceId: "collegym-studios", sportId: "gymnastics" },
  { spaceId: "collegym-studios", sportId: "dance" },
  { spaceId: "country-poleg-pool", sportId: "swimming" },
  { spaceId: "country-poleg-tennis-courts", sportId: "tennis" },
  { spaceId: "winter-lake-futsal-field", sportId: "futsal" },
  { spaceId: "winter-lake-skatepark", sportId: "skateboarding" },
  { spaceId: "winter-lake-skatepark", sportId: "roller_skating" },
  { spaceId: "sportek-yahalom-roller-court", sportId: "roller_skating" },
  { spaceId: "sportek-yahalom-combined", sportId: "basketball" },
  { spaceId: "sportek-yahalom-combined", sportId: "futsal" },
  { spaceId: "olimp-swim-lanes", sportId: "swimming" },
  { spaceId: "crossfit-green-beach-floor", sportId: "crossfit" },
  { spaceId: "crossfit-green-beach-floor", sportId: "fitness" },
  { spaceId: "crossfit-green-beach-floor", sportId: "gymnastics" },
  { spaceId: "maccabi-netanya-football-training", sportId: "football" },
] as const;

const coaches = [
  {
    bio: text("מאמנת טניס עירונית לילדים ומתחילים", "Городской тренер по теннису для детей и начинающих", "Municipal tennis coach for children and beginners"),
    facilityId: "gali-yam-tennis",
    id: "coach-yael-beckman",
    languages: ["he", "ru", "en"],
    maxAge: 99,
    minAge: 7,
    name: text("יעל בקמן", "Яэль Бекман", "Yael Beckman"),
    sourceUrl: sourceUrls.tennisClass,
    sports: [text("טניס", "Теннис", "Tennis")],
  },
  {
    bio: text("מאמן כדורסל בנות במרכז ישורון", "Тренер секции баскетбола для девочек в Ешурун", "Girls basketball coach at Yeshurun"),
    facilityId: "yeshurun-basketball",
    id: "coach-shahar-frank",
    languages: ["he"],
    maxAge: 12,
    minAge: 7,
    name: text("שחר פרנק", "Шахар Франк", "Shahar Frank"),
    sourceUrl: sourceUrls.girlsBasketball,
    sports: [text("כדורסל", "Баскетбол", "Basketball")],
  },
  {
    bio: text("צוות מדריכי שחייה - נדרש שיוך מדריך ספציפי", "Команда тренеров по плаванию - нужен конкретный тренер", "Swimming coaching team - specific coach assignment needed"),
    facilityId: "olimp-swimming-netanya",
    id: "coach-olimp-team",
    languages: ["he", "ru"],
    maxAge: 120,
    minAge: 3,
    name: text("צוות אולימפ", "Команда Olimp", "Olimp team"),
    sourceUrl: sourceUrls.olimp,
    sports: [text("שחייה", "Плавание", "Swimming")],
  },
  {
    bio: text("צוות קרוספיט, ילדים ונוער", "Команда CrossFit, дети и подростки", "CrossFit, kids, and youth coaching team"),
    facilityId: "crossfit-green-beach",
    id: "coach-crossfit-green-beach-team",
    languages: ["he", "en"],
    maxAge: 99,
    minAge: 6,
    name: text("צוות קרוספיט גרין ביץ'", "Команда CrossFit Green Beach", "CrossFit Green Beach team"),
    sourceUrl: sourceUrls.crossfitGreenBeach,
    sports: [text("קרוספיט", "Кроссфит", "CrossFit")],
  },
] as const;

const programs = [
  {
    capacity: 12,
    coachId: "coach-yael-beckman",
    description: text("חוג פעמיים בשבוע לילדים שמתחילים טניס", "Секция два раза в неделю для детей, начинающих теннис", "Twice-weekly class for children starting tennis"),
    facilityId: "gali-yam-tennis",
    id: "program-gali-yam-kids-tennis",
    maxAge: 12,
    minAge: 7,
    recurrence: text("שלישי וחמישי", "Вторник и четверг", "Tuesday and Thursday"),
    remainingMirror: 4,
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.tennisClass,
    spaceId: "gali-yam-training-courts",
    sportId: "tennis",
    title: text("חוג טניס מתחילים", "Секция тенниса для начинающих", "Beginner tennis class"),
  },
  {
    capacity: 18,
    coachId: "coach-shahar-frank",
    description: text("קבוצת כדורסל בנות לכיתות ד-ו", "Группа баскетбола для девочек 4-6 классов", "Girls basketball group for grades 4-6"),
    facilityId: "yeshurun-basketball",
    id: "program-yeshurun-girls-basketball",
    maxAge: 12,
    minAge: 7,
    recurrence: text("שלישי וחמישי", "Вторник и четверг", "Tuesday and Thursday"),
    remainingMirror: 5,
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.girlsBasketball,
    spaceId: "yeshurun-main-hall",
    sportId: "basketball",
    title: text("כדורסל בנות", "Баскетбол для девочек", "Girls basketball"),
  },
  {
    capacity: 16,
    coachId: null,
    description: text("ליגת כדורסל למבוגרים", "Баскетбольная лига для взрослых", "Adult basketball league"),
    facilityId: "yeshurun-basketball",
    id: "program-yeshurun-adult-basketball",
    maxAge: 99,
    minAge: 18,
    recurrence: text("א-ה בערב", "Вс-Чт вечером", "Sun-Thu evenings"),
    remainingMirror: 2,
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.yeshurun,
    spaceId: "yeshurun-main-hall",
    sportId: "basketball",
    title: text("כדורסל מבוגרים", "Баскетбол для взрослых", "Adult basketball"),
  },
  {
    capacity: 14,
    coachId: null,
    description: text("ג'ודו לילדים בבית ספר ביאליק", "Дзюдо для детей в школе Бялик", "Children's judo at Bialik"),
    facilityId: "bialik-judo",
    id: "program-bialik-judo",
    maxAge: 12,
    minAge: 6,
    recurrence: text("שני ורביעי", "Понедельник и среда", "Monday and Wednesday"),
    remainingMirror: 4,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.bialik,
    spaceId: "bialik-dojo-space",
    sportId: "judo",
    title: text("ג'ודו", "Дзюдо", "Judo"),
  },
  {
    capacity: 12,
    coachId: null,
    description: text("קורס ילדים במרכז רב-תחומי; צריך לייבא מערכת שעות אמיתית", "Детская секция в мультиспорт-центре; нужно импортировать реальное расписание", "Children program at a multi-sport center; real timetable import needed"),
    facilityId: "collegym-netanya",
    id: "program-collegym-kids-multisport",
    maxAge: 12,
    minAge: 5,
    recurrence: text("עונת 2025-2026", "Сезон 2025-2026", "2025-2026 season"),
    remainingMirror: 6,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.collegym,
    spaceId: "collegym-studios",
    sportId: "gymnastics",
    title: text("ילדים - ג'ודו, קפוארה, התעמלות ומחול", "Дети - дзюдо, капоэйра, гимнастика и танцы", "Kids - judo, capoeira, gymnastics, and dance"),
  },
  {
    capacity: 10,
    coachId: null,
    description: text("חוגי שחייה ושיעורים פרטיים מגיל 5", "Плавание и частные уроки с 5 лет", "Swimming classes and private lessons from age 5"),
    facilityId: "country-club-poleg",
    id: "program-country-poleg-swimming",
    maxAge: 120,
    minAge: 5,
    recurrence: text("לפי מסלול והרשמה", "По программе и регистрации", "By track and registration"),
    remainingMirror: 4,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.countryPoleg,
    spaceId: "country-poleg-pool",
    sportId: "swimming",
    title: text("שחייה לילדים ומבוגרים", "Плавание для детей и взрослых", "Swimming for children and adults"),
  },
  {
    capacity: 8,
    coachId: "coach-olimp-team",
    description: text("קבוצות שחייה לילדים, שיעורים פרטיים ומאסטרס", "Группы плавания для детей, частные уроки и masters", "Children groups, private lessons, and masters swimming"),
    facilityId: "olimp-swimming-netanya",
    id: "program-olimp-children-swimming",
    maxAge: 120,
    minAge: 3,
    recurrence: text("הרשמה עונתית", "Сезонная регистрация", "Season registration"),
    remainingMirror: 3,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.olimp,
    spaceId: "olimp-swim-lanes",
    sportId: "swimming",
    title: text("שחייה לילדים ומאסטרס", "Плавание для детей и masters", "Children and masters swimming"),
  },
  {
    capacity: 12,
    coachId: "coach-crossfit-green-beach-team",
    description: text("קבוצות קרוספיט לילדים ונוער", "Группы CrossFit для детей и подростков", "CrossFit groups for children and youth"),
    facilityId: "crossfit-green-beach",
    id: "program-crossfit-green-beach-kids",
    maxAge: 17,
    minAge: 6,
    recurrence: text("לפי מערכת המועדון", "По расписанию клуба", "By club timetable"),
    remainingMirror: 5,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.crossfitGreenBeach,
    spaceId: "crossfit-green-beach-floor",
    sportId: "crossfit",
    title: text("קרוספיט ילדים ונוער", "CrossFit дети и подростки", "CrossFit kids and youth"),
  },
  {
    capacity: 18,
    coachId: null,
    description: text("בית ספר לכדורגל לגילים צעירים; דורש אימות תאריכי עונה", "Футбольная школа для младших возрастов; даты сезона требуют проверки", "Football school for young age groups; season dates need verification"),
    facilityId: "maccabi-netanya-football-school",
    id: "program-maccabi-netanya-football-school",
    maxAge: 16,
    minAge: 4,
    recurrence: text("עונת 2025-2026 - לבדיקה", "Сезон 2025-2026 - проверить", "2025-2026 season - verify"),
    remainingMirror: 8,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.netanyaMunicipality,
    spaceId: "maccabi-netanya-football-training",
    sportId: "football",
    title: text("בית ספר לכדורגל", "Футбольная школа", "Football school"),
  },
] as const;

const offerings = [
  {
    capacity: 1,
    coachId: null,
    description: text("השכרת מגרש אחד ל-60 דקות", "Аренда одного корта на 60 минут", "One-court 60-minute rental"),
    facilityId: "gali-yam-tennis",
    id: "gali-yam-court-rental",
    kind: "court_rental",
    maxAge: 99,
    minAge: 18,
    priceAgorot: 4500,
    programId: null,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.galiYam,
    spaceId: "gali-yam-court-01-space",
    sportId: "tennis",
    title: text("השכרת מגרש טניס", "Аренда теннисного корта", "Tennis court rental"),
  },
  {
    capacity: 1,
    coachId: "coach-yael-beckman",
    description: text("אימון פרטי על אותו מגרש פיזי", "Индивидуальная тренировка на том же физическом корте", "Private coaching on the same physical court"),
    facilityId: "gali-yam-tennis",
    id: "gali-yam-private-coach",
    kind: "coach_session",
    maxAge: 99,
    minAge: 12,
    priceAgorot: 9000,
    programId: null,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.tennisClass,
    spaceId: "gali-yam-court-01-space",
    sportId: "tennis",
    title: text("אימון טניס פרטי", "Индивидуальная тренировка по теннису", "Private tennis coaching"),
  },
  {
    capacity: 12,
    coachId: "coach-yael-beckman",
    description: text("קבוצת ילדים מתחילים", "Детская группа начинающих", "Beginner children's group"),
    facilityId: "gali-yam-tennis",
    id: "gali-yam-kids-tennis",
    kind: "group_class",
    maxAge: 12,
    minAge: 7,
    priceAgorot: 22000,
    programId: "program-gali-yam-kids-tennis",
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.tennisClass,
    spaceId: "gali-yam-training-courts",
    sportId: "tennis",
    title: text("חוג טניס מתחילים", "Секция тенниса для начинающих", "Beginner tennis class"),
  },
  {
    capacity: 2,
    coachId: null,
    description: text("שימוש ציבורי חופשי", "Свободное общественное использование", "Free public use"),
    facilityId: "ovadia-tennis-courts",
    id: "ovadia-public-tennis",
    kind: "court_rental",
    maxAge: 99,
    minAge: 0,
    priceAgorot: 0,
    programId: null,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.ovadia,
    spaceId: "ovadia-public-courts-space",
    sportId: "tennis",
    title: text("שימוש ציבורי חינם", "Бесплатное публичное использование", "Free public use"),
  },
  {
    capacity: 20,
    coachId: null,
    description: text("משחק חופשי במגרש משולב", "Свободная игра на комбинированной площадке", "Open play on a combined court"),
    facilityId: "sportek-ir-yamim-court",
    id: "sportek-open-play-offering",
    kind: "open_play",
    maxAge: 99,
    minAge: 0,
    priceAgorot: 0,
    programId: null,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.sportek,
    spaceId: "sportek-combined-court-space",
    sportId: "basketball",
    title: text("כדורסל / קטרגל", "Баскетбол / футзал", "Basketball / futsal"),
  },
  {
    capacity: 18,
    coachId: "coach-shahar-frank",
    description: text("קבוצת כדורסל בנות", "Группа баскетбола для девочек", "Girls basketball group"),
    facilityId: "yeshurun-basketball",
    id: "yeshurun-girls-basketball-offering",
    kind: "group_class",
    maxAge: 12,
    minAge: 7,
    priceAgorot: 22500,
    programId: "program-yeshurun-girls-basketball",
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.girlsBasketball,
    spaceId: "yeshurun-main-hall",
    sportId: "basketball",
    title: text("כדורסל בנות", "Баскетбол для девочек", "Girls basketball"),
  },
  {
    capacity: 16,
    coachId: null,
    description: text("ליגת מבוגרים", "Взрослая лига", "Adult league"),
    facilityId: "yeshurun-basketball",
    id: "yeshurun-adult-basketball-offering",
    kind: "group_class",
    maxAge: 99,
    minAge: 18,
    priceAgorot: null,
    programId: "program-yeshurun-adult-basketball",
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.yeshurun,
    spaceId: "yeshurun-main-hall",
    sportId: "basketball",
    title: text("כדורסל מבוגרים", "Баскетбол для взрослых", "Adult basketball"),
  },
  {
    capacity: 1,
    coachId: null,
    description: text("שימוש חובבים באולם", "Любительская аренда зала", "Amateur hall use"),
    facilityId: "yeshurun-basketball",
    id: "yeshurun-hall-basketball-rental",
    kind: "court_rental",
    maxAge: 99,
    minAge: 16,
    priceAgorot: null,
    programId: null,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.yeshurunHall,
    spaceId: "yeshurun-main-hall",
    sportId: "basketball",
    title: text("השכרת אולם לכדורסל", "Аренда зала для баскетбола", "Basketball hall rental"),
  },
  {
    capacity: 16,
    coachId: null,
    description: text("טאקוונדו", "Тхэквондо", "Taekwondo"),
    facilityId: "stakelis-sports-center",
    id: "stakelis-taekwondo-offering",
    kind: "group_class",
    maxAge: 17,
    minAge: 7,
    priceAgorot: null,
    programId: null,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.stakelis,
    spaceId: "stakelis-gym-space",
    sportId: "taekwondo",
    title: text("טאקוונדו", "Тхэквондо", "Taekwondo"),
  },
  {
    capacity: 14,
    coachId: null,
    description: text("ג'ודו", "Дзюдо", "Judo"),
    facilityId: "bialik-judo",
    id: "bialik-judo-offering",
    kind: "group_class",
    maxAge: 12,
    minAge: 6,
    priceAgorot: null,
    programId: "program-bialik-judo",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.bialik,
    spaceId: "bialik-dojo-space",
    sportId: "judo",
    title: text("ג'ודו", "Дзюдо", "Judo"),
  },
  {
    capacity: 10,
    coachId: null,
    description: text("ספורט מותאם", "Адаптированный спорт", "Adapted sport"),
    facilityId: "adapted-sport-tamar-ariel",
    id: "adapted-sport-offering",
    kind: "group_class",
    maxAge: 99,
    minAge: 4,
    priceAgorot: null,
    programId: null,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.adaptedSport,
    spaceId: "tamar-ariel-adapted-space",
    sportId: "adapted_sport",
    title: text("ספורט מותאם", "Адаптированный спорт", "Adapted sport"),
  },
  {
    capacity: 1,
    coachId: null,
    description: text("הזמנת מגרש פאדל ל-90 דקות דרך מקור חיצוני", "Бронирование корта падела на 90 минут через внешний источник", "90-minute padel court booking through external source"),
    facilityId: "top-padel-ir-yamim",
    id: "top-padel-ir-yamim-court-rental",
    kind: "court_rental",
    maxAge: 99,
    minAge: 16,
    priceAgorot: null,
    programId: null,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.topPadel,
    spaceId: "top-padel-ir-yamim-court-01",
    sportId: "padel",
    title: text("השכרת מגרש פאדל", "Аренда корта падела", "Padel court rental"),
  },
  {
    capacity: 4,
    coachId: null,
    description: text("משחק פתוח למציאת שותפים בפאדל", "Открытая игра для поиска партнёров по паделу", "Open match for padel partner matching"),
    facilityId: "top-padel-ir-yamim",
    id: "top-padel-ir-yamim-open-match",
    kind: "open_play",
    maxAge: 99,
    minAge: 16,
    priceAgorot: null,
    programId: null,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.topPadel,
    spaceId: "top-padel-ir-yamim-court-01",
    sportId: "padel",
    title: text("משחק פאדל פתוח", "Открытая игра в падел", "Open padel match"),
  },
  {
    capacity: 1,
    coachId: null,
    description: text("הזמנת מגרש פאדל בפולג", "Бронирование корта падела в Полег", "Padel court booking in Poleg"),
    facilityId: "top-padel-poleg",
    id: "top-padel-poleg-court-rental",
    kind: "court_rental",
    maxAge: 99,
    minAge: 16,
    priceAgorot: null,
    programId: null,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.topPadel,
    spaceId: "top-padel-poleg-court-01",
    sportId: "padel",
    title: text("השכרת מגרש פאדל פולג", "Аренда корта падела Полег", "Poleg padel court rental"),
  },
  {
    capacity: 12,
    coachId: null,
    description: text("ילדים - חוגים רב-תחומיים", "Детские мультиспорт-секции", "Children multi-sport classes"),
    facilityId: "collegym-netanya",
    id: "collegym-kids-multisport-offering",
    kind: "group_class",
    maxAge: 12,
    minAge: 5,
    priceAgorot: null,
    programId: "program-collegym-kids-multisport",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.collegym,
    spaceId: "collegym-studios",
    sportId: "gymnastics",
    title: text("חוגי ילדים בקולג'ים", "Детские секции Collegym", "Collegym kids classes"),
  },
  {
    capacity: 10,
    coachId: null,
    description: text("שחייה לילדים ומבוגרים", "Плавание для детей и взрослых", "Swimming for children and adults"),
    facilityId: "country-club-poleg",
    id: "country-poleg-swimming-offering",
    kind: "group_class",
    maxAge: 120,
    minAge: 5,
    priceAgorot: null,
    programId: "program-country-poleg-swimming",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.countryPoleg,
    spaceId: "country-poleg-pool",
    sportId: "swimming",
    title: text("חוג שחייה", "Секция плавания", "Swimming class"),
  },
  {
    capacity: 20,
    coachId: null,
    description: text("שימוש ציבורי במגרש פוטסל", "Публичное использование поля футзала", "Public futsal field use"),
    facilityId: "winter-lake-sports-park",
    id: "winter-lake-futsal-open-play",
    kind: "open_play",
    maxAge: 99,
    minAge: 0,
    priceAgorot: 0,
    programId: null,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.netanyaMunicipality,
    spaceId: "winter-lake-futsal-field",
    sportId: "futsal",
    title: text("פוטסל ציבורי", "Публичный футзал", "Public futsal"),
  },
  {
    capacity: 30,
    coachId: null,
    description: text("שימוש חופשי בסקייטפארק", "Свободное использование скейтпарка", "Free skatepark use"),
    facilityId: "winter-lake-sports-park",
    id: "winter-lake-skatepark-open-use",
    kind: "open_play",
    maxAge: 99,
    minAge: 0,
    priceAgorot: 0,
    programId: null,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.netanyaMunicipality,
    spaceId: "winter-lake-skatepark",
    sportId: "skateboarding",
    title: text("סקייטפארק ציבורי", "Публичный скейтпарк", "Public skatepark"),
  },
  {
    capacity: 18,
    coachId: null,
    description: text("שימוש חופשי במגרש רולר", "Свободное использование роллер-площадки", "Free roller court use"),
    facilityId: "sportek-yahalom",
    id: "sportek-yahalom-roller-open-use",
    kind: "open_play",
    maxAge: 99,
    minAge: 0,
    priceAgorot: 0,
    programId: null,
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.netanyaMunicipality,
    spaceId: "sportek-yahalom-roller-court",
    sportId: "roller_skating",
    title: text("רולר ציבורי", "Публичные ролики", "Public roller skating"),
  },
  {
    capacity: 8,
    coachId: "coach-olimp-team",
    description: text("קבוצות שחייה לילדים ומאסטרס", "Группы плавания для детей и masters", "Children and masters swimming groups"),
    facilityId: "olimp-swimming-netanya",
    id: "olimp-children-swimming-offering",
    kind: "group_class",
    maxAge: 120,
    minAge: 3,
    priceAgorot: null,
    programId: "program-olimp-children-swimming",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.olimp,
    spaceId: "olimp-swim-lanes",
    sportId: "swimming",
    title: text("קבוצות שחייה", "Группы плавания", "Swimming groups"),
  },
  {
    capacity: 1,
    coachId: "coach-olimp-team",
    description: text("שיעור שחייה פרטי", "Частный урок плавания", "Private swimming lesson"),
    facilityId: "olimp-swimming-netanya",
    id: "olimp-private-swim-lesson",
    kind: "coach_session",
    maxAge: 120,
    minAge: 3,
    priceAgorot: null,
    programId: null,
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.olimp,
    spaceId: "olimp-swim-lanes",
    sportId: "swimming",
    title: text("שיעור שחייה פרטי", "Частный урок плавания", "Private swimming lesson"),
  },
  {
    capacity: 12,
    coachId: "coach-crossfit-green-beach-team",
    description: text("קרוספיט ילדים ונוער", "CrossFit для детей и подростков", "CrossFit for kids and youth"),
    facilityId: "crossfit-green-beach",
    id: "crossfit-green-beach-kids-offering",
    kind: "group_class",
    maxAge: 17,
    minAge: 6,
    priceAgorot: null,
    programId: "program-crossfit-green-beach-kids",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.crossfitGreenBeach,
    spaceId: "crossfit-green-beach-floor",
    sportId: "crossfit",
    title: text("קרוספיט ילדים ונוער", "CrossFit дети и подростки", "CrossFit kids and youth"),
  },
  {
    capacity: 18,
    coachId: null,
    description: text("בית ספר לכדורגל - בדיקת תאריכים לפני פרסום", "Футбольная школа - проверить даты перед публикацией", "Football school - verify dates before publishing"),
    facilityId: "maccabi-netanya-football-school",
    id: "maccabi-netanya-football-school-offering",
    kind: "group_class",
    maxAge: 16,
    minAge: 4,
    priceAgorot: null,
    programId: "program-maccabi-netanya-football-school",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.netanyaMunicipality,
    spaceId: "maccabi-netanya-football-training",
    sportId: "football",
    title: text("בית ספר לכדורגל", "Футбольная школа", "Football school"),
  },
] as const;

const openMatches = [
  {
    capacity: 4,
    confirmedPlayers: 2,
    endsAt: "2026-06-19T17:30:00.000Z",
    facilityId: "gali-yam-tennis",
    id: "open-match-gali-yam-tennis-1930",
    level: text("מתחילים+", "Начальный+", "Beginner+"),
    maxAge: 99,
    minAge: 18,
    sourceConfidence: "manual_review",
    spaceId: "gali-yam-court-01-space",
    sportId: "tennis",
    startsAt: "2026-06-19T16:30:00.000Z",
    title: text("מחפשים זוג לטניס", "Ищем пару для тенниса", "Looking for tennis partners"),
  },
  {
    capacity: 10,
    confirmedPlayers: 6,
    endsAt: "2026-06-18T19:00:00.000Z",
    facilityId: "sportek-ir-yamim-court",
    id: "open-match-sportek-basketball",
    level: text("חובבים", "Любители", "Casual"),
    maxAge: 99,
    minAge: 16,
    sourceConfidence: "official_info",
    spaceId: "sportek-combined-court-space",
    sportId: "basketball",
    startsAt: "2026-06-18T18:00:00.000Z",
    title: text("משחק כדורסל פתוח", "Открытая игра в баскетбол", "Open basketball run"),
  },
  {
    capacity: 4,
    confirmedPlayers: 2,
    endsAt: "2026-06-19T18:00:00.000Z",
    facilityId: "top-padel-ir-yamim",
    id: "open-match-top-padel-ir-yamim-evening",
    level: text("מתחילים עד בינוני", "Начальный-средний", "Beginner to intermediate"),
    maxAge: 99,
    minAge: 16,
    sourceConfidence: "manual_review",
    spaceId: "top-padel-ir-yamim-court-01",
    sportId: "padel",
    startsAt: "2026-06-19T16:30:00.000Z",
    title: text("מחפשים זוג לפאדל", "Ищем пару для падела", "Looking for padel partners"),
  },
] as const;

const resources = [
  {
    capacity: 1,
    description: text(
      "השכרת מגרש אחד ל-60 דקות",
      "Аренда одного корта на 60 минут",
      "One-court 60-minute rental",
    ),
    exclusiveUse: true,
    facilityId: "gali-yam-tennis",
    id: "gali-yam-court-01",
    kind: "court_rental",
    maxAge: 99,
    minAge: 18,
    name: text("מגרש טניס 1", "Теннисный корт 1", "Tennis court 1"),
    offeringId: "gali-yam-court-rental",
    sourceConfidence: "manual_review",
    spaceId: "gali-yam-court-01-space",
    sportId: "tennis",
  },
  {
    capacity: 1,
    description: text(
      "אימון פרטי על מגרש 1",
      "Индивидуальная тренировка на корте 1",
      "Private coaching on court 1",
    ),
    exclusiveUse: true,
    facilityId: "gali-yam-tennis",
    id: "gali-yam-private-coach-resource",
    kind: "coach_session",
    maxAge: 99,
    minAge: 12,
    name: text("אימון פרטי - יעל בקמן", "Индивидуально - Яэль Бекман", "Private coaching - Yael Beckman"),
    offeringId: "gali-yam-private-coach",
    sourceConfidence: "manual_review",
    spaceId: "gali-yam-court-01-space",
    sportId: "tennis",
  },
  {
    capacity: 12,
    description: text("חוג ילדים מתחילים", "Детская группа начинающих", "Beginner children's class"),
    exclusiveUse: false,
    facilityId: "gali-yam-tennis",
    id: "gali-yam-kids-tennis-resource",
    kind: "group_class",
    maxAge: 12,
    minAge: 7,
    name: text("טניס ילדים - יעל בקמן", "Теннис для детей - Яэль Бекман", "Children's tennis - Yael Beckman"),
    offeringId: "gali-yam-kids-tennis",
    sourceConfidence: "operator_confirmed",
    spaceId: "gali-yam-training-courts",
    sportId: "tennis",
  },
  {
    capacity: 2,
    description: text("שימוש ציבורי", "Публичное использование", "Public use"),
    exclusiveUse: false,
    facilityId: "ovadia-tennis-courts",
    id: "ovadia-public-courts-resource",
    kind: "court_rental",
    maxAge: 99,
    minAge: 0,
    name: text("מגרשי עובדיה", "Корты Овадия", "Ovadia courts"),
    offeringId: "ovadia-public-tennis",
    sourceConfidence: "official_info",
    spaceId: "ovadia-public-courts-space",
    sportId: "tennis",
  },
  {
    capacity: 20,
    description: text("משחק חופשי", "Свободная игра", "Open play"),
    exclusiveUse: false,
    facilityId: "sportek-ir-yamim-court",
    id: "sportek-open-play-resource",
    kind: "open_play",
    maxAge: 99,
    minAge: 0,
    name: text("מגרש משולב", "Комбинированная площадка", "Combined court"),
    offeringId: "sportek-open-play-offering",
    sourceConfidence: "official_info",
    spaceId: "sportek-combined-court-space",
    sportId: "basketball",
  },
  {
    capacity: 18,
    description: text("כדורסל בנות", "Баскетбол для девочек", "Girls basketball"),
    exclusiveUse: false,
    facilityId: "yeshurun-basketball",
    id: "yeshurun-girls-basketball-resource",
    kind: "group_class",
    maxAge: 12,
    minAge: 7,
    name: text("כדורסל בנות - שחר פרנק", "Баскетбол для девочек - Шахар Франк", "Girls basketball - Shahar Frank"),
    offeringId: "yeshurun-girls-basketball-offering",
    sourceConfidence: "operator_confirmed",
    spaceId: "yeshurun-main-hall",
    sportId: "basketball",
  },
  {
    capacity: 16,
    description: text("ליגת מבוגרים", "Взрослая лига", "Adult league"),
    exclusiveUse: false,
    facilityId: "yeshurun-basketball",
    id: "yeshurun-adult-basketball-resource",
    kind: "group_class",
    maxAge: 99,
    minAge: 18,
    name: text("כדורסל מבוגרים", "Баскетбол для взрослых", "Adult basketball"),
    offeringId: "yeshurun-adult-basketball-offering",
    sourceConfidence: "operator_confirmed",
    spaceId: "yeshurun-main-hall",
    sportId: "basketball",
  },
  {
    capacity: 1,
    description: text("שימוש חובבים באולם", "Любительская аренда зала", "Amateur hall use"),
    exclusiveUse: true,
    facilityId: "yeshurun-basketball",
    id: "yeshurun-hall-resource",
    kind: "court_rental",
    maxAge: 99,
    minAge: 16,
    name: text("אולם ישורון", "Зал Ешурун", "Yeshurun hall"),
    offeringId: "yeshurun-hall-basketball-rental",
    sourceConfidence: "official_info",
    spaceId: "yeshurun-main-hall",
    sportId: "basketball",
  },
  {
    capacity: 16,
    description: text("טאקוונדו", "Тхэквондо", "Taekwondo"),
    exclusiveUse: false,
    facilityId: "stakelis-sports-center",
    id: "stakelis-taekwondo-resource",
    kind: "group_class",
    maxAge: 17,
    minAge: 7,
    name: text("טאקוונדו סטקליס", "Тхэквондо Стакелис", "Stakelis Taekwondo"),
    offeringId: "stakelis-taekwondo-offering",
    sourceConfidence: "official_info",
    spaceId: "stakelis-gym-space",
    sportId: "taekwondo",
  },
  {
    capacity: 14,
    description: text("ג'ודו", "Дзюдо", "Judo"),
    exclusiveUse: false,
    facilityId: "bialik-judo",
    id: "bialik-judo-resource",
    kind: "group_class",
    maxAge: 12,
    minAge: 6,
    name: text("ג'ודו ביאליק", "Дзюдо Бялик", "Bialik Judo"),
    offeringId: "bialik-judo-offering",
    sourceConfidence: "official_info",
    spaceId: "bialik-dojo-space",
    sportId: "judo",
  },
  {
    capacity: 10,
    description: text("ספורט מותאם", "Адаптированный спорт", "Adapted sport"),
    exclusiveUse: false,
    facilityId: "adapted-sport-tamar-ariel",
    id: "adapted-sport-resource",
    kind: "group_class",
    maxAge: 99,
    minAge: 4,
    name: text("ספורט מותאם", "Адаптированный спорт", "Adapted sport"),
    offeringId: "adapted-sport-offering",
    sourceConfidence: "official_info",
    spaceId: "tamar-ariel-adapted-space",
    sportId: "adapted_sport",
  },
  {
    capacity: 1,
    description: text("הזמנת מגרש פאדל", "Аренда корта падела", "Padel court rental"),
    exclusiveUse: true,
    facilityId: "top-padel-ir-yamim",
    id: "top-padel-ir-yamim-court-resource",
    kind: "court_rental",
    maxAge: 99,
    minAge: 16,
    name: text("מגרש פאדל עיר ימים", "Корт падела Ир-Ямим", "Ir Yamim padel court"),
    offeringId: "top-padel-ir-yamim-court-rental",
    sourceConfidence: "manual_review",
    spaceId: "top-padel-ir-yamim-court-01",
    sportId: "padel",
  },
  {
    capacity: 4,
    description: text("משחק פתוח", "Открытая игра", "Open match"),
    exclusiveUse: false,
    facilityId: "top-padel-ir-yamim",
    id: "top-padel-ir-yamim-open-match-resource",
    kind: "open_play",
    maxAge: 99,
    minAge: 16,
    name: text("משחק פאדל פתוח", "Открытый падел", "Open padel"),
    offeringId: "top-padel-ir-yamim-open-match",
    sourceConfidence: "manual_review",
    spaceId: "top-padel-ir-yamim-court-01",
    sportId: "padel",
  },
  {
    capacity: 1,
    description: text("הזמנת מגרש פאדל פולג", "Аренда корта падела Полег", "Poleg padel court rental"),
    exclusiveUse: true,
    facilityId: "top-padel-poleg",
    id: "top-padel-poleg-court-resource",
    kind: "court_rental",
    maxAge: 99,
    minAge: 16,
    name: text("מגרש פאדל פולג", "Корт падела Полег", "Poleg padel court"),
    offeringId: "top-padel-poleg-court-rental",
    sourceConfidence: "manual_review",
    spaceId: "top-padel-poleg-court-01",
    sportId: "padel",
  },
  {
    capacity: 12,
    description: text("חוגי ילדים קולג'ים", "Детские секции Collegym", "Collegym kids classes"),
    exclusiveUse: false,
    facilityId: "collegym-netanya",
    id: "collegym-kids-multisport-resource",
    kind: "group_class",
    maxAge: 12,
    minAge: 5,
    name: text("חוגי ילדים", "Детские секции", "Kids classes"),
    offeringId: "collegym-kids-multisport-offering",
    sourceConfidence: "manual_review",
    spaceId: "collegym-studios",
    sportId: "gymnastics",
  },
  {
    capacity: 10,
    description: text("חוג שחייה קאנטרי פולג", "Плавание Country Poleg", "Country Poleg swimming"),
    exclusiveUse: false,
    facilityId: "country-club-poleg",
    id: "country-poleg-swimming-resource",
    kind: "group_class",
    maxAge: 120,
    minAge: 5,
    name: text("שחייה", "Плавание", "Swimming"),
    offeringId: "country-poleg-swimming-offering",
    sourceConfidence: "manual_review",
    spaceId: "country-poleg-pool",
    sportId: "swimming",
  },
  {
    capacity: 20,
    description: text("פוטסל ציבורי", "Публичный футзал", "Public futsal"),
    exclusiveUse: false,
    facilityId: "winter-lake-sports-park",
    id: "winter-lake-futsal-resource",
    kind: "open_play",
    maxAge: 99,
    minAge: 0,
    name: text("מגרש פוטסל", "Поле футзала", "Futsal field"),
    offeringId: "winter-lake-futsal-open-play",
    sourceConfidence: "official_info",
    spaceId: "winter-lake-futsal-field",
    sportId: "futsal",
  },
  {
    capacity: 30,
    description: text("סקייטפארק ציבורי", "Публичный скейтпарк", "Public skatepark"),
    exclusiveUse: false,
    facilityId: "winter-lake-sports-park",
    id: "winter-lake-skatepark-resource",
    kind: "open_play",
    maxAge: 99,
    minAge: 0,
    name: text("סקייטפארק", "Скейтпарк", "Skatepark"),
    offeringId: "winter-lake-skatepark-open-use",
    sourceConfidence: "official_info",
    spaceId: "winter-lake-skatepark",
    sportId: "skateboarding",
  },
  {
    capacity: 18,
    description: text("רולר ציבורי", "Публичные ролики", "Public roller skating"),
    exclusiveUse: false,
    facilityId: "sportek-yahalom",
    id: "sportek-yahalom-roller-resource",
    kind: "open_play",
    maxAge: 99,
    minAge: 0,
    name: text("מגרש רולר", "Роллер-площадка", "Roller court"),
    offeringId: "sportek-yahalom-roller-open-use",
    sourceConfidence: "official_info",
    spaceId: "sportek-yahalom-roller-court",
    sportId: "roller_skating",
  },
  {
    capacity: 8,
    description: text("קבוצות שחייה אולימפ", "Группы плавания Olimp", "Olimp swimming groups"),
    exclusiveUse: false,
    facilityId: "olimp-swimming-netanya",
    id: "olimp-children-swimming-resource",
    kind: "group_class",
    maxAge: 120,
    minAge: 3,
    name: text("קבוצות שחייה", "Группы плавания", "Swimming groups"),
    offeringId: "olimp-children-swimming-offering",
    sourceConfidence: "manual_review",
    spaceId: "olimp-swim-lanes",
    sportId: "swimming",
  },
  {
    capacity: 1,
    description: text("שיעור שחייה פרטי", "Частный урок плавания", "Private swimming lesson"),
    exclusiveUse: true,
    facilityId: "olimp-swimming-netanya",
    id: "olimp-private-swim-resource",
    kind: "coach_session",
    maxAge: 120,
    minAge: 3,
    name: text("שיעור פרטי", "Частный урок", "Private lesson"),
    offeringId: "olimp-private-swim-lesson",
    sourceConfidence: "manual_review",
    spaceId: "olimp-swim-lanes",
    sportId: "swimming",
  },
  {
    capacity: 12,
    description: text("קרוספיט ילדים ונוער", "CrossFit дети и подростки", "CrossFit kids and youth"),
    exclusiveUse: false,
    facilityId: "crossfit-green-beach",
    id: "crossfit-green-beach-kids-resource",
    kind: "group_class",
    maxAge: 17,
    minAge: 6,
    name: text("קרוספיט ילדים", "CrossFit дети", "CrossFit kids"),
    offeringId: "crossfit-green-beach-kids-offering",
    sourceConfidence: "manual_review",
    spaceId: "crossfit-green-beach-floor",
    sportId: "crossfit",
  },
  {
    capacity: 18,
    description: text("בית ספר לכדורגל", "Футбольная школа", "Football school"),
    exclusiveUse: false,
    facilityId: "maccabi-netanya-football-school",
    id: "maccabi-netanya-football-school-resource",
    kind: "group_class",
    maxAge: 16,
    minAge: 4,
    name: text("אימון כדורגל", "Футбольная тренировка", "Football training"),
    offeringId: "maccabi-netanya-football-school-offering",
    sourceConfidence: "manual_review",
    spaceId: "maccabi-netanya-football-training",
    sportId: "football",
  },
] as const;

const slots = [
  {
    capacity: 1,
    confirmedUnits: 0,
    endsAt: "2026-06-18T16:30:00.000Z",
    heldUnits: 0,
    id: "gali-yam-demo-adult-court",
    priceAgorot: 4500,
    remainingMirror: 1,
    resourceId: "gali-yam-court-01",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.galiYam,
    startsAt: "2026-06-18T15:30:00.000Z",
    title: text("מגרש טניס 60 דקות", "Теннисный корт на 60 минут", "60-minute tennis court"),
  },
  {
    capacity: 1,
    confirmedUnits: 0,
    endsAt: "2026-06-18T16:30:00.000Z",
    heldUnits: 0,
    id: "gali-yam-private-coach-overlap",
    priceAgorot: 9000,
    remainingMirror: 1,
    resourceId: "gali-yam-private-coach-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.tennisClass,
    startsAt: "2026-06-18T15:30:00.000Z",
    title: text("אימון טניס פרטי - אותו מגרש", "Индивидуальная тренировка - тот же корт", "Private tennis coaching - same court"),
  },
  {
    capacity: 1,
    confirmedUnits: 0,
    endsAt: "2026-06-18T17:30:00.000Z",
    heldUnits: 0,
    id: "gali-yam-demo-adult-court-1930",
    priceAgorot: 4500,
    remainingMirror: 1,
    resourceId: "gali-yam-court-01",
    sourceConfidence: "live_inventory",
    sourceUrl: sourceUrls.galiYam,
    startsAt: "2026-06-18T16:30:00.000Z",
    title: text("מגרש טניס 60 דקות - 19:30", "Теннисный корт на 60 минут - 19:30", "60-minute tennis court - 19:30"),
  },
  {
    capacity: 1,
    confirmedUnits: 0,
    endsAt: "2026-06-19T16:30:00.000Z",
    heldUnits: 0,
    id: "gali-yam-demo-adult-court-next-day",
    priceAgorot: 4500,
    remainingMirror: 1,
    resourceId: "gali-yam-court-01",
    sourceConfidence: "live_inventory",
    sourceUrl: sourceUrls.galiYam,
    startsAt: "2026-06-19T15:30:00.000Z",
    title: text("מגרש טניס 60 דקות - מחר", "Теннисный корт на 60 минут - завтра", "60-minute tennis court - tomorrow"),
  },
  {
    capacity: 12,
    confirmedUnits: 8,
    endsAt: "2026-06-23T14:45:00.000Z",
    heldUnits: 0,
    id: "gali-yam-beginner-kids",
    priceAgorot: 22000,
    remainingMirror: 4,
    resourceId: "gali-yam-kids-tennis-resource",
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.tennisClass,
    startsAt: "2026-06-23T14:00:00.000Z",
    title: text("חוג טניס מתחילים", "Секция тенниса для начинающих", "Beginner tennis class"),
  },
  {
    capacity: 12,
    confirmedUnits: 6,
    endsAt: "2026-06-25T14:45:00.000Z",
    heldUnits: 0,
    id: "gali-yam-beginner-kids-thu",
    priceAgorot: 22000,
    remainingMirror: 6,
    resourceId: "gali-yam-kids-tennis-resource",
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.tennisClass,
    startsAt: "2026-06-25T14:00:00.000Z",
    title: text("חוג טניס מתחילים - חמישי", "Секция тенниса для начинающих - четверг", "Beginner tennis class - Thursday"),
  },
  {
    capacity: 2,
    confirmedUnits: 0,
    endsAt: "2026-06-18T19:00:00.000Z",
    heldUnits: 0,
    id: "ovadia-free-public",
    priceAgorot: 0,
    remainingMirror: 2,
    resourceId: "ovadia-public-courts-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.ovadia,
    startsAt: "2026-06-18T18:00:00.000Z",
    title: text("שימוש ציבורי חינם", "Бесплатное публичное использование", "Free public use"),
  },
  {
    capacity: 20,
    confirmedUnits: 11,
    endsAt: "2026-06-18T18:00:00.000Z",
    heldUnits: 0,
    id: "sportek-open-play",
    priceAgorot: 0,
    remainingMirror: 9,
    resourceId: "sportek-open-play-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.sportek,
    startsAt: "2026-06-18T17:00:00.000Z",
    title: text("כדורסל / קטרגל", "Баскетбол / футзал", "Basketball / futsal"),
  },
  {
    capacity: 18,
    confirmedUnits: 13,
    endsAt: "2026-06-23T13:45:00.000Z",
    heldUnits: 0,
    id: "yeshurun-girls-basketball",
    priceAgorot: 22500,
    remainingMirror: 5,
    resourceId: "yeshurun-girls-basketball-resource",
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.girlsBasketball,
    startsAt: "2026-06-23T13:00:00.000Z",
    title: text("חוג כדורסל בנות", "Секция баскетбола для девочек", "Girls basketball class"),
  },
  {
    capacity: 18,
    confirmedUnits: 12,
    endsAt: "2026-06-25T13:45:00.000Z",
    heldUnits: 0,
    id: "yeshurun-girls-basketball-thu",
    priceAgorot: 22500,
    remainingMirror: 6,
    resourceId: "yeshurun-girls-basketball-resource",
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.girlsBasketball,
    startsAt: "2026-06-25T13:00:00.000Z",
    title: text("חוג כדורסל בנות - חמישי", "Секция баскетбола для девочек - четверг", "Girls basketball class - Thursday"),
  },
  {
    capacity: 16,
    confirmedUnits: 14,
    endsAt: "2026-06-21T18:00:00.000Z",
    heldUnits: 0,
    id: "yeshurun-adult-basketball",
    priceAgorot: null,
    remainingMirror: 2,
    resourceId: "yeshurun-adult-basketball-resource",
    sourceConfidence: "operator_confirmed",
    sourceUrl: sourceUrls.yeshurun,
    startsAt: "2026-06-21T16:00:00.000Z",
    title: text("כדורסל מבוגרים", "Баскетбол для взрослых", "Adult basketball"),
  },
  {
    capacity: 1,
    confirmedUnits: 0,
    endsAt: "2026-06-21T18:30:00.000Z",
    heldUnits: 0,
    id: "yeshurun-hall-request",
    priceAgorot: null,
    remainingMirror: 1,
    resourceId: "yeshurun-hall-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.yeshurunHall,
    startsAt: "2026-06-21T17:00:00.000Z",
    title: text("שימוש חובבים באולם", "Любительская аренда зала", "Amateur hall use"),
  },
  {
    capacity: 16,
    confirmedUnits: 10,
    endsAt: "2026-06-21T18:00:00.000Z",
    heldUnits: 0,
    id: "stakelis-taekwondo",
    priceAgorot: null,
    remainingMirror: 6,
    resourceId: "stakelis-taekwondo-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.stakelis,
    startsAt: "2026-06-21T17:00:00.000Z",
    title: text("טאקוונדו", "Тхэквондо", "Taekwondo"),
  },
  {
    capacity: 14,
    confirmedUnits: 10,
    endsAt: "2026-06-22T15:15:00.000Z",
    heldUnits: 0,
    id: "bialik-judo-mon-wed",
    priceAgorot: null,
    remainingMirror: 4,
    resourceId: "bialik-judo-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.bialik,
    startsAt: "2026-06-22T13:45:00.000Z",
    title: text("ג'ודו", "Дзюдо", "Judo"),
  },
  {
    capacity: 10,
    confirmedUnits: 7,
    endsAt: "2026-06-21T15:00:00.000Z",
    heldUnits: 0,
    id: "adapted-youth-sunday",
    priceAgorot: null,
    remainingMirror: 3,
    resourceId: "adapted-sport-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.adaptedSport,
    startsAt: "2026-06-21T14:15:00.000Z",
    title: text("ספורט מותאם לנוער", "Адаптированный спорт для подростков", "Adapted youth sport"),
  },
  {
    capacity: 10,
    confirmedUnits: 8,
    endsAt: "2026-06-21T15:45:00.000Z",
    heldUnits: 0,
    id: "adapted-adults-sunday",
    priceAgorot: null,
    remainingMirror: 2,
    resourceId: "adapted-sport-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.adaptedSport,
    startsAt: "2026-06-21T15:00:00.000Z",
    title: text("ספורט מותאם למבוגרים", "Адаптированный спорт для взрослых", "Adapted adult sport"),
  },
  {
    capacity: 8,
    confirmedUnits: 6,
    endsAt: "2026-06-23T15:45:00.000Z",
    heldUnits: 0,
    id: "adapted-capoeira-kids",
    priceAgorot: null,
    remainingMirror: 2,
    resourceId: "adapted-sport-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.adaptedSport,
    startsAt: "2026-06-23T15:00:00.000Z",
    title: text("קפוארה לילדים", "Капоэйра для детей", "Children's capoeira"),
  },
  {
    capacity: 1,
    confirmedUnits: 0,
    endsAt: "2026-06-18T19:00:00.000Z",
    heldUnits: 0,
    id: "top-padel-ir-yamim-evening-court",
    priceAgorot: null,
    remainingMirror: 1,
    resourceId: "top-padel-ir-yamim-court-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.topPadel,
    startsAt: "2026-06-18T17:30:00.000Z",
    title: text("מגרש פאדל - בדיקת זמינות", "Корт падела - проверить доступность", "Padel court - check availability"),
  },
  {
    capacity: 4,
    confirmedUnits: 2,
    endsAt: "2026-06-19T18:00:00.000Z",
    heldUnits: 0,
    id: "top-padel-ir-yamim-open-match-slot",
    priceAgorot: null,
    remainingMirror: 2,
    resourceId: "top-padel-ir-yamim-open-match-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.topPadel,
    startsAt: "2026-06-19T16:30:00.000Z",
    title: text("משחק פאדל פתוח", "Открытая игра в падел", "Open padel match"),
  },
  {
    capacity: 1,
    confirmedUnits: 0,
    endsAt: "2026-06-19T18:30:00.000Z",
    heldUnits: 0,
    id: "top-padel-poleg-court-slot",
    priceAgorot: null,
    remainingMirror: 1,
    resourceId: "top-padel-poleg-court-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.topPadel,
    startsAt: "2026-06-19T17:00:00.000Z",
    title: text("מגרש פאדל פולג - בדיקת זמינות", "Корт падела Полег - проверить доступность", "Poleg padel court - check availability"),
  },
  {
    capacity: 12,
    confirmedUnits: 6,
    endsAt: "2026-06-22T15:45:00.000Z",
    heldUnits: 0,
    id: "collegym-kids-multisport-slot",
    priceAgorot: null,
    remainingMirror: 6,
    resourceId: "collegym-kids-multisport-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.collegym,
    startsAt: "2026-06-22T15:00:00.000Z",
    title: text("חוגי ילדים בקולג'ים", "Детские секции Collegym", "Collegym kids classes"),
  },
  {
    capacity: 10,
    confirmedUnits: 6,
    endsAt: "2026-06-23T14:45:00.000Z",
    heldUnits: 0,
    id: "country-poleg-swimming-slot",
    priceAgorot: null,
    remainingMirror: 4,
    resourceId: "country-poleg-swimming-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.countryPoleg,
    startsAt: "2026-06-23T14:00:00.000Z",
    title: text("שחייה לילדים ומבוגרים", "Плавание для детей и взрослых", "Swimming for children and adults"),
  },
  {
    capacity: 20,
    confirmedUnits: 8,
    endsAt: "2026-06-18T20:00:00.000Z",
    heldUnits: 0,
    id: "winter-lake-futsal-evening",
    priceAgorot: 0,
    remainingMirror: 12,
    resourceId: "winter-lake-futsal-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.netanyaMunicipality,
    startsAt: "2026-06-18T19:00:00.000Z",
    title: text("פוטסל ציבורי", "Публичный футзал", "Public futsal"),
  },
  {
    capacity: 30,
    confirmedUnits: 18,
    endsAt: "2026-06-18T21:00:00.000Z",
    heldUnits: 0,
    id: "winter-lake-skatepark-open",
    priceAgorot: 0,
    remainingMirror: 12,
    resourceId: "winter-lake-skatepark-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.netanyaMunicipality,
    startsAt: "2026-06-18T20:00:00.000Z",
    title: text("סקייטפארק ציבורי", "Публичный скейтпарк", "Public skatepark"),
  },
  {
    capacity: 18,
    confirmedUnits: 7,
    endsAt: "2026-06-18T18:30:00.000Z",
    heldUnits: 0,
    id: "sportek-yahalom-roller-open",
    priceAgorot: 0,
    remainingMirror: 11,
    resourceId: "sportek-yahalom-roller-resource",
    sourceConfidence: "official_info",
    sourceUrl: sourceUrls.netanyaMunicipality,
    startsAt: "2026-06-18T17:30:00.000Z",
    title: text("רולר ציבורי", "Публичные ролики", "Public roller skating"),
  },
  {
    capacity: 8,
    confirmedUnits: 5,
    endsAt: "2026-06-24T14:45:00.000Z",
    heldUnits: 0,
    id: "olimp-children-swimming-slot",
    priceAgorot: null,
    remainingMirror: 3,
    resourceId: "olimp-children-swimming-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.olimp,
    startsAt: "2026-06-24T14:00:00.000Z",
    title: text("קבוצת שחייה לילדים", "Группа плавания для детей", "Children swimming group"),
  },
  {
    capacity: 1,
    confirmedUnits: 0,
    endsAt: "2026-06-24T15:30:00.000Z",
    heldUnits: 0,
    id: "olimp-private-swim-slot",
    priceAgorot: null,
    remainingMirror: 1,
    resourceId: "olimp-private-swim-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.olimp,
    startsAt: "2026-06-24T15:00:00.000Z",
    title: text("שיעור שחייה פרטי", "Частный урок плавания", "Private swimming lesson"),
  },
  {
    capacity: 12,
    confirmedUnits: 7,
    endsAt: "2026-06-22T16:45:00.000Z",
    heldUnits: 0,
    id: "crossfit-green-beach-kids-slot",
    priceAgorot: null,
    remainingMirror: 5,
    resourceId: "crossfit-green-beach-kids-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.crossfitGreenBeach,
    startsAt: "2026-06-22T16:00:00.000Z",
    title: text("קרוספיט ילדים ונוער", "CrossFit дети и подростки", "CrossFit kids and youth"),
  },
  {
    capacity: 18,
    confirmedUnits: 10,
    endsAt: "2026-06-23T15:30:00.000Z",
    heldUnits: 0,
    id: "maccabi-netanya-football-school-slot",
    priceAgorot: null,
    remainingMirror: 8,
    resourceId: "maccabi-netanya-football-school-resource",
    sourceConfidence: "manual_review",
    sourceUrl: sourceUrls.netanyaMunicipality,
    startsAt: "2026-06-23T14:30:00.000Z",
    title: text("בית ספר לכדורגל - לבדיקה", "Футбольная школа - проверить", "Football school - verify"),
  },
] as const;

const dataVerificationTasks = [
  {
    facilityId: "top-padel-ir-yamim",
    id: "verify-top-padel-booking-sync",
    notes: text("בדוק אם ניתן לקבל API/ICS/CSV לסלוטים וסטטוס תשלום לפני הפעלת תשלום מקומי.", "Проверить API/ICS/CSV слотов и статус оплаты перед локальной оплатой.", "Check API/ICS/CSV slot access and payment state before enabling local payment."),
    priority: "critical",
    sourceUrl: sourceUrls.topPadel,
    title: text("אימות סנכרון Top Padel", "Проверить синхронизацию Top Padel", "Verify Top Padel sync"),
  },
  {
    facilityId: "collegym-netanya",
    id: "verify-collegym-dedupe",
    notes: text("אחד את Collegym ו-Sports Center at Netanya Academic College כישות אחת אם זה אותו מפעיל.", "Объединить Collegym и Sports Center at Netanya Academic College, если это один оператор.", "Merge Collegym and Netanya Academic College Sports Center if they are the same operator."),
    priority: "high",
    sourceUrl: sourceUrls.collegym,
    title: text("בדיקת כפילות Collegym", "Проверить дубль Collegym", "Check Collegym duplicate"),
  },
  {
    facilityId: "winter-lake-sports-park",
    id: "verify-winter-lake-futsal-rules",
    notes: text("אשר אם הפוטסל דורש הזמנה מוקדמת ומהי דרך ההזמנה העירונית.", "Подтвердить, нужна ли предварительная бронь футзала и как она работает.", "Confirm whether futsal requires advance booking and the municipal booking path."),
    priority: "high",
    sourceUrl: sourceUrls.netanyaMunicipality,
    title: text("כללי הזמנה באגם החורף", "Правила брони Winter Lake", "Winter Lake booking rules"),
  },
  {
    facilityId: "sportek-yahalom",
    id: "verify-sportek-yahalom-hours",
    notes: text("אמת שעות תאורה 17:00-23:00, זמינות רולר ומגרש משולב.", "Проверить освещение 17:00-23:00, ролики и combined court.", "Verify lighting hours 17:00-23:00, roller court, and combined court availability."),
    priority: "medium",
    sourceUrl: sourceUrls.netanyaMunicipality,
    title: text("אימות ספורטק יהלום", "Проверить Sportek Yahalom", "Verify Sportek Yahalom"),
  },
  {
    facilityId: "olimp-swimming-netanya",
    id: "verify-olimp-swim-schedule",
    notes: text("קבל לוח קבוצות לפי גיל, private lesson windows ושיטת תשלום.", "Получить расписание групп по возрастам, окна private lessons и способ оплаты.", "Get age-group timetable, private lesson windows, and payment method."),
    priority: "high",
    sourceUrl: sourceUrls.olimp,
    title: text("אימות לוח שחייה Olimp", "Проверить расписание Olimp", "Verify Olimp swimming timetable"),
  },
  {
    facilityId: "maccabi-netanya-football-school",
    id: "verify-maccabi-season-dates",
    notes: text("בדוק סתירות בין דף הרשמה עונתי לתאריכי העונה לפני הצגה כ-live registration.", "Проверить противоречия дат сезонной регистрации перед live registration.", "Check seasonal registration date conflicts before showing as live registration."),
    priority: "critical",
    sourceUrl: sourceUrls.netanyaMunicipality,
    title: text("אימות תאריכי מכבי נתניה", "Проверить даты Maccabi Netanya", "Verify Maccabi Netanya dates"),
  },
  {
    organizationId: "org-regaim",
    id: "verify-regaim-import-feed",
    notes: text("מצא דרך ייבוא Hugim/Regaim לעונה 2025-2026: גיל, מחיר, מרכז, קישור הרשמה.", "Найти импорт Hugim/Regaim на сезон 2025-2026: возраст, цена, центр, регистрация.", "Find Hugim/Regaim import path for 2025-2026: age, price, center, registration link."),
    priority: "high",
    sourceUrl: sourceUrls.regaim,
    title: text("ייבוא חוגי Regaim", "Импорт кружков Regaim", "Import Regaim classes"),
  },
] as const;

async function main() {
  const facilityIds = facilities.map((facility) => facility.id);
  const coachIds = coaches.map((coach) => coach.id);
  const dataVerificationTaskIds = dataVerificationTasks.map((task) => task.id);
  const offeringIds = offerings.map((offering) => offering.id);
  const openMatchIds = openMatches.map((openMatch) => openMatch.id);
  const organizationIds = organizations.map((organization) => organization.id);
  const programIds = programs.map((program) => program.id);
  const resourceIds = resources.map((resource) => resource.id);
  const slotIds = slots.map((slot) => slot.id);
  const spaceIds = spaces.map((space) => space.id);
  const sportIds = sports.map((sport) => sport.id);
  const resourceById = new Map(resources.map((resource) => [resource.id, resource]));
  const now = new Date();

  await prisma.$transaction(async (tx) => {
    await tx.dataVerificationTask.deleteMany({ where: { id: { in: dataVerificationTaskIds } } });
    await tx.paymentEvent.deleteMany({});
    await tx.paymentIntent.deleteMany({});
    await tx.bookingOccupancy.deleteMany({});
    await tx.booking.deleteMany({});
    await tx.bookingHold.deleteMany({});
    await tx.waitlistEntry.deleteMany({
      where: {
        OR: [
          { facilityId: { in: facilityIds } },
          { programId: { in: programIds } },
          { slotId: { in: slotIds } },
        ],
      },
    });
    await tx.userFollow.deleteMany({
      where: {
        OR: [
          { facilityId: { in: facilityIds } },
          { coachId: { in: coachIds } },
          { programId: { in: programIds } },
        ],
      },
    });
    await tx.openMatch.deleteMany({ where: { id: { in: openMatchIds } } });
    await tx.slotCapacity.deleteMany({ where: { slotId: { in: slotIds } } });
    await tx.bookingSlot.deleteMany({ where: { id: { in: slotIds } } });
    await tx.inventoryResource.deleteMany({ where: { id: { in: resourceIds } } });
    await tx.offering.deleteMany({ where: { id: { in: offeringIds } } });
    await tx.program.deleteMany({ where: { id: { in: programIds } } });
    await tx.coachProfile.deleteMany({ where: { id: { in: coachIds } } });
    await tx.spaceSportCapability.deleteMany({ where: { spaceId: { in: spaceIds } } });
    await tx.facilitySpace.deleteMany({ where: { id: { in: spaceIds } } });
    await tx.sourceSnapshot.deleteMany({ where: { facilityId: { in: facilityIds } } });
    await tx.facility.deleteMany({ where: { id: { in: facilityIds } } });
    await tx.organization.deleteMany({ where: { id: { in: organizationIds } } });
    await tx.sport.deleteMany({ where: { id: { in: sportIds } } });

    await tx.userAccount.upsert({
      create: {
        email: "demo-resident@sportil.local",
        id: "demo-resident",
        name: text("משתמש דמו", "Демо-житель", "Demo resident"),
        role: "resident",
      },
      update: {
        name: text("משתמש דמו", "Демо-житель", "Demo resident"),
        role: "resident",
      },
      where: { id: "demo-resident" },
    });

    await tx.organization.createMany({
      data: organizations.map((organization) => ({
        description: organization.description,
        id: organization.id,
        kind: organization.kind,
        name: organization.name,
        sourceNotes: {
          importedBy: "seed",
          researchDate: "2026-06-18",
        },
        sourceType: organization.sourceType,
        sourceUrl: organization.sourceUrl,
        verificationStatus: organization.verificationStatus,
        websiteUrl: "websiteUrl" in organization ? organization.websiteUrl : null,
      })),
    });

    await tx.facility.createMany({
      data: facilities.map((facility) => ({
        ...(facilityMetadata[facility.id as keyof typeof facilityMetadata] ?? {}),
        address: facility.address,
        externalId: `netanya:${facility.id}`,
        id: facility.id,
        kind: facility.kind,
        name: facility.name,
        neighborhood: facility.neighborhood,
        sourceCheckedAt: checkedAt,
        sourceUrl: facility.sourceUrl,
        status: facility.status,
        lastVerifiedAt: checkedAt,
      })),
    });

    await tx.sport.createMany({
      data: sports.map((sport) => ({
        icon: sport.icon,
        id: sport.id,
        name: sport.name,
      })),
    });

    await tx.facilitySpace.createMany({
      data: spaces.map((space) => ({
        capacity: space.capacity,
        description: space.description,
        facilityId: space.facilityId,
        id: space.id,
        indoor: space.indoor,
        name: space.name,
        surface: space.surface,
      })),
    });

    await tx.spaceSportCapability.createMany({
      data: spaceSportCapabilities.map((capability) => ({
        spaceId: capability.spaceId,
        sportId: capability.sportId,
      })),
    });

    await tx.coachProfile.createMany({
      data: coaches.map((coach) => ({
        bio: coach.bio,
        facilityId: coach.facilityId,
        id: coach.id,
        languages: coach.languages,
        maxAge: coach.maxAge,
        minAge: coach.minAge,
        name: coach.name,
        sourceUrl: coach.sourceUrl,
        sports: coach.sports,
      })),
    });

    await tx.program.createMany({
      data: programs.map((program) => {
        const metadata = facilityMetadata[program.facilityId as keyof typeof facilityMetadata];

        return {
          bookingMethod: metadata?.bookingMethod ?? "contact_request",
          capacity: program.capacity,
          coachId: program.coachId,
          confidenceScore: metadata?.confidenceScore,
          description: program.description,
          externalRegistrationUrl: metadata?.externalRegistrationUrl,
          facilityId: program.facilityId,
          id: program.id,
          lastVerifiedAt: checkedAt,
          maxAge: program.maxAge,
          minAge: program.minAge,
          organizationId: metadata?.organizationId,
          paymentMethod: metadata?.paymentMethod ?? "unknown",
          recurrence: program.recurrence,
          remainingMirror: program.remainingMirror,
          sourceConfidence: program.sourceConfidence,
          sourceNotes: metadata?.sourceNotes,
          sourceUrl: program.sourceUrl,
          spaceId: program.spaceId,
          sportId: program.sportId,
          syncStatus: "fresh",
          title: program.title,
          verificationStatus: metadata?.verificationStatus ?? "info_only",
        };
      }),
    });

    await tx.offering.createMany({
      data: offerings.map((offering) => {
        const metadata = facilityMetadata[offering.facilityId as keyof typeof facilityMetadata];

        return {
          bookingMethod: metadata?.bookingMethod ?? "contact_request",
          capacity: offering.capacity,
          coachId: offering.coachId,
          confidenceScore: metadata?.confidenceScore,
          description: offering.description,
          externalRegistrationUrl: metadata?.externalRegistrationUrl,
          facilityId: offering.facilityId,
          id: offering.id,
          kind: offering.kind,
          lastVerifiedAt: checkedAt,
          maxAge: offering.maxAge,
          minAge: offering.minAge,
          organizationId: metadata?.organizationId,
          paymentMethod: metadata?.paymentMethod ?? "unknown",
          priceAgorot: offering.priceAgorot,
          programId: offering.programId,
          sourceConfidence: offering.sourceConfidence,
          sourceNotes: metadata?.sourceNotes,
          sourceUrl: offering.sourceUrl,
          spaceId: offering.spaceId,
          sportId: offering.sportId,
          syncStatus: "fresh",
          title: offering.title,
          verificationStatus: metadata?.verificationStatus ?? "info_only",
        };
      }),
    });

    await tx.inventoryResource.createMany({
      data: resources.map((resource) => ({
        capacity: resource.capacity,
        description: resource.description,
        exclusiveUse: resource.exclusiveUse,
        facilityId: resource.facilityId,
        id: resource.id,
        kind: resource.kind,
        maxAge: resource.maxAge,
        minAge: resource.minAge,
        name: resource.name,
        offeringId: resource.offeringId,
        sourceConfidence: resource.sourceConfidence,
        spaceId: resource.spaceId,
        sportId: resource.sportId,
        syncStatus: "fresh",
      })),
    });

    await tx.bookingSlot.createMany({
      data: slots.map((slot) => ({
        capacity: slot.capacity,
        endsAt: new Date(slot.endsAt),
        id: slot.id,
        offeringId: resourceById.get(slot.resourceId)?.offeringId,
        priceAgorot: slot.priceAgorot,
        remainingMirror: slot.remainingMirror,
        resourceId: slot.resourceId,
        sourceConfidence: slot.sourceConfidence,
        sourceUrl: slot.sourceUrl,
        startsAt: new Date(slot.startsAt),
        syncStatus: "fresh",
        title: slot.title,
      })),
    });

    await tx.openMatch.createMany({
      data: openMatches.map((openMatch) => ({
        capacity: openMatch.capacity,
        confirmedPlayers: openMatch.confirmedPlayers,
        endsAt: new Date(openMatch.endsAt),
        facilityId: openMatch.facilityId,
        id: openMatch.id,
        level: openMatch.level,
        maxAge: openMatch.maxAge,
        minAge: openMatch.minAge,
        sourceConfidence: openMatch.sourceConfidence,
        spaceId: openMatch.spaceId,
        sportId: openMatch.sportId,
        startsAt: new Date(openMatch.startsAt),
        status: "open",
        title: openMatch.title,
      })),
    });

    await tx.slotCapacity.createMany({
      data: slots.map((slot) => ({
        capacity: slot.capacity,
        confirmedUnits: slot.confirmedUnits,
        heldUnits: slot.heldUnits,
        slotId: slot.id,
        updatedAt: now,
      })),
    });

    await tx.sourceSnapshot.createMany({
      data: facilities.map((facility) => ({
        facilityId: facility.id,
        payloadRedacted: {
          checkedBy: "seed",
          sourceName: netanyaMunicipality,
          verification: facilityMetadata[facility.id]?.verificationStatus ?? "info_only",
        },
        sourceConfidence: facility.status === "bookable" ? "manual_review" : "official_info",
        sourceObservedAt: checkedAt,
        sourceUrl: facility.sourceUrl,
        syncStatus: "fresh",
      })),
    });

    await tx.dataVerificationTask.createMany({
      data: dataVerificationTasks.map((task) => ({
        facilityId: "facilityId" in task ? task.facilityId : undefined,
        id: task.id,
        notes: task.notes,
        organizationId: "organizationId" in task ? task.organizationId : undefined,
        priority: task.priority,
        sourceUrl: task.sourceUrl,
        status: "open",
        title: task.title,
      })),
    });
  });

  console.info(
    `Seeded SportIL demo catalog: ${organizations.length} organizations, ${facilities.length} facilities, ${spaces.length} spaces, ${offerings.length} offerings, ${resources.length} resources, ${slots.length} slots, ${dataVerificationTasks.length} verification tasks.`,
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
