import type { LocalizedText, SportCode } from "@sportil/types";

function text(he: string, ru: string, en: string): LocalizedText {
  return { en, he, ru };
}

export const sportLabels: Record<SportCode, LocalizedText> = {
  adapted_sport: text("ספורט מותאם", "Адаптированный спорт", "Adapted sport"),
  aquathlon: text("אקוותלון", "Акватлон", "Aquathlon"),
  athletics: text("אתלטיקה", "Легкая атлетика", "Athletics"),
  basketball: text("כדורסל", "Баскетбол", "Basketball"),
  badminton: text("בדמינטון", "Бадминтон", "Badminton"),
  bjj: text("ג׳יו ג׳יטסו ברזילאי", "BJJ / джиу-джитсу", "BJJ / Jiu-jitsu"),
  boxing: text("אגרוף", "Бокс", "Boxing"),
  calisthenics: text("קליסטניקס", "Калистеника", "Calisthenics"),
  capoeira: text("קפוארה", "Капоэйра", "Capoeira"),
  climbing: text("טיפוס", "Скалолазание", "Climbing"),
  crossfit: text("קרוספיט", "Кроссфит", "CrossFit"),
  dance: text("מחול", "Танцы", "Dance"),
  figure_skating: text("החלקה אמנותית", "Фигурное катание", "Figure skating"),
  fitness: text("כושר", "Фитнес", "Fitness"),
  football: text("כדורגל", "Футбол", "Football"),
  futsal: text("קטרגל", "Футзал", "Futsal"),
  gymnastics: text("התעמלות", "Гимнастика", "Gymnastics"),
  handball: text("כדוריד", "Гандбол", "Handball"),
  hockey: text("הוקי", "Хоккей", "Hockey"),
  hydrotherapy: text("הידרותרפיה", "Гидротерапия", "Hydrotherapy"),
  hyrox: text("HYROX", "HYROX", "HYROX"),
  ice_skating: text("החלקה על הקרח", "Катание на льду", "Ice skating"),
  judo: text("ג'ודו", "Дзюдо", "Judo"),
  karate: text("קראטה", "Карате", "Karate"),
  kickboxing: text("קיקבוקס", "Кикбоксинг", "Kickboxing"),
  krav_maga: text("קרב מגע", "Крав-мага", "Krav Maga"),
  lawn_bowls: text("בולס דשא", "Боулз", "Lawn bowls"),
  mma: text("MMA", "MMA", "MMA"),
  padel: text("פאדל", "Падел", "Padel"),
  pilates: text("פילאטיס", "Пилатес", "Pilates"),
  roller_skating: text("רולר", "Ролики", "Roller skating"),
  sambo: text("סמבו", "Самбо", "Sambo"),
  skateboarding: text("סקייטבורד", "Скейтборд", "Skateboarding"),
  spinning: text("ספינינג", "Spinning", "Spinning"),
  swimming: text("שחייה", "Плавание", "Swimming"),
  table_tennis: text("טניס שולחן", "Настольный теннис", "Table tennis"),
  taekwondo: text("טאקוונדו", "Тхэквондо", "Taekwondo"),
  tennis: text("טניס", "Теннис", "Tennis"),
  trx: text("TRX", "TRX", "TRX"),
  volleyball: text("כדורעף", "Волейбол", "Volleyball"),
  weightlifting: text("הרמת משקולות", "Тяжелая атлетика", "Weightlifting"),
  wrestling: text("היאבקות", "Борьба", "Wrestling"),
  yoga: text("יוגה", "Йога", "Yoga"),
  zumba: text("זומבה", "Зумба", "Zumba"),
};
